In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.1.1-cp312-cp312-macosx_14_0_arm64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp312-cp312-macosx_11_0_arm64.whl (11.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 26.1 MB/s eta 0:00:00 0:00:01
Downloading numpy-2.1.1-cp312-cp312-macosx_14_0_arm64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 32.3 MB/s eta 0:00:00
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.1.1 pandas-2.2.2 pytz-2024.1 tzdata-2024.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

# Merging all the excel files into single file

In [1]:
import pandas as pd
import json

In [2]:
df_bangalore = pd.read_excel("csv files/bangalore_cars.xlsx")
df_bangalore["City"] = 'Bangalore'
df_chennai = pd.read_excel("csv files/chennai_cars.xlsx")
df_chennai["City"] = 'Chennai'
df_delhi = pd.read_excel("csv files/delhi_cars.xlsx")
df_delhi["City"] = "Delhi"
df_hyderabad = pd.read_excel("csv files/hyderabad_cars.xlsx")
df_hyderabad["City"] = "Hyderabad"
df_jaipur = pd.read_excel("csv files/jaipur_cars.xlsx")
df_jaipur["City"] = "Jaipur"
df_kolkata = pd.read_excel("csv files/kolkata_cars.xlsx")
df_kolkata["City"] = "Kolkata"

merged_df = pd.concat([df_bangalore,df_chennai,df_delhi,df_hyderabad,df_jaipur,df_kolkata], ignore_index=True)

In [3]:
merged_df

,new_car_detail,new_car_overview,new_car_feature,new_car_specs,car_links,City
0,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
1,"{'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Bangalore
2,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
3,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/buy-used-car-details/...,Bangalore
4,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Bangalore
...,...,...,...,...,...,...
8364,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8365,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8366,"{'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8367,"{'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata
8368,"{'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...","{'heading': 'Car overview', 'top': [{'key': 'R...","{'heading': 'Features', 'top': [{'value': 'Pow...","{'heading': 'Specifications', 'top': [{'key': ...",https://www.cardekho.com/used-car-details/used...,Kolkata

In [4]:
merged_df.to_excel("merged/combined_excel_file.xlsx")

# splitting and working on the columnwise

In [5]:
merged_df.to_json("merged/merged_data.json")

In [6]:
data = pd.read_json("merged/merged_data.json")

In [7]:
df_newcar = data["new_car_detail"]
df_newcar

0       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1       {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
2       {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
3       {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
4       {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
                              ...
8364    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
8365    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
8366    {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
8367    {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
8368    {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
Name: new_car_detail, Length: 8369, dtype: object

In [8]:
df_new_car_detail = pd.DataFrame(df_newcar)
df_new_car_detail

                                         new_car_detail
0     {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
1     {'it': 0, 'ft': 'Petrol', 'bt': 'SUV', 'km': '...
2     {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
3     {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
4     {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...
...                                                 ...
8364  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
8365  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
8366  {'it': 0, 'ft': 'Petrol', 'bt': 'Sedan', 'km':...
8367  {'it': 0, 'ft': 'Petrol', 'bt': 'Hatchback', '...
8368  {'it': 0, 'ft': 'Diesel', 'bt': 'SUV', 'km': '...

[8369 rows x 1 columns]

In [9]:
import ast
df_new_car_detail['new_car_detail'] = df_new_car_detail['new_car_detail'].apply(ast.literal_eval)

# Normalize the 'new_car_detail' data
car_details_normalized_data = pd.json_normalize(df_new_car_detail['new_car_detail'])

car_details_normalized_data

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,centralVariantId,variantName,price,priceActual,priceSaving,priceFixedText,trendingText.imgUrl,trendingText.heading,trendingText.desc
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,3979,VXI,₹ 4 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,₹ 8.11 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,₹ 5.85 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,₹ 4.62 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,₹ 7.90 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,8682,ZXI BSVI,₹ 5.10 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8365,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,3943,LXI,₹ 1.80 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8366,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,4672,C 200 CGI Elegance,₹ 5.50 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8367,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,4144,ZXi,₹ 1.40 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days
8368,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,5048,110PS Diesel RxZ AWD,₹ 5 Lakh,,,None,https://stimg.cardekho.com/used-cars/common/ic...,Trending Car!,High chances of sale in next 6 days

In [10]:
data.columns

Index(['new_car_detail', 'new_car_overview', 'new_car_feature',
       'new_car_specs', 'car_links', 'City'],
      dtype='object')

In [11]:
df_overview = data["new_car_overview"]
df_new_car_overview = pd.DataFrame(df_overview)

df_new_car_overview['new_car_overview'] = df_new_car_overview['new_car_overview'].apply(ast.literal_eval)

# Extract the 'top' data and create columns from the keys
top_data = df_new_car_overview['new_car_overview'].apply(lambda x: {item['key']: item['value'] for item in x['top']})

# Convert the dictionary of 'top' data to a DataFrame
car_overview_normalized_data = pd.DataFrame(top_data.tolist())

# Display the resulting DataFrame
car_overview_normalized_data

,Registration Year,Insurance Validity,Fuel Type,Seats,Kms Driven,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture
0,2015,Third Party insurance,Petrol,5 Seats,"1,20,000 Kms",KA51,Third Owner,998 cc,Manual,2015.0
1,Feb 2018,Comprehensive,Petrol,5 Seats,"32,706 Kms",KA05,Second Owner,1497 cc,Manual,2018.0
2,Sept 2018,Comprehensive,Petrol,5 Seats,"11,949 Kms",KA03,First Owner,1199 cc,Manual,2018.0
3,Dec 2014,Comprehensive,Petrol,5 Seats,"17,794 Kms",KA53,First Owner,1197 cc,Manual,2014.0
4,2015,Third Party insurance,Diesel,5 Seats,"60,000 Kms",KA04,First Owner,1248 cc,Manual,2015.0
...,...,...,...,...,...,...,...,...,...,...
8364,2022,Third Party insurance,Petrol,5 Seats,"10,000 Kms",NaN,First Owner,998 cc,Manual,2022.0
8365,2014,Third Party insurance,Petrol,5 Seats,"1,20,000 Kms",NaN,First Owner,796 cc,Manual,2014.0
8366,2011,Third Party insurance,Petrol,5 Seats,"50,000 Kms",WB06,Third Owner,1796 cc,Automatic,2011.0
8367,2012,Third Party insurance,Petrol,5 Seats,"40,000 Kms",NaN,First Owner,1197 cc,Manual,2012.0
8368,2017,Third Party insurance,Diesel,5 Seats,"1,20,000 Kms",NaN,Second Owner,1461 cc,Manual,2017.0

In [13]:
df_car_feature = data['new_car_feature']
df_new_car_feature = pd.DataFrame(df_car_feature)

df_new_car_feature

                                        new_car_feature
0     {'heading': 'Features', 'top': [{'value': 'Pow...
1     {'heading': 'Features', 'top': [{'value': 'Pow...
2     {'heading': 'Features', 'top': [{'value': 'Pow...
3     {'heading': 'Features', 'top': [{'value': 'Pow...
4     {'heading': 'Features', 'top': [{'value': 'Pow...
...                                                 ...
8364  {'heading': 'Features', 'top': [{'value': 'Pow...
8365  {'heading': 'Features', 'top': [{'value': 'Pow...
8366  {'heading': 'Features', 'top': [{'value': 'Pow...
8367  {'heading': 'Features', 'top': [{'value': 'Pow...
8368  {'heading': 'Features', 'top': [{'value': 'Pow...

[8369 rows x 1 columns]

In [14]:

# Ensure 'new_car_feature' is a dictionary (convert from string if needed)
if df_new_car_feature['new_car_feature'].apply(type).eq(str).any():
    df_new_car_feature['new_car_feature'] = df_new_car_feature['new_car_feature'].apply(ast.literal_eval)

# Initialize an empty dictionary to hold column data
columns = {}

# Process the 'top' data
df_new_car_feature['top'] = df_new_car_feature['new_car_feature'].apply(lambda x: x.get('top', []))
columns['Features'] = df_new_car_feature['top'].apply(len)

# Process the 'data' field
df_new_car_feature['data'] = df_new_car_feature['new_car_feature'].apply(lambda x: x.get('data', []))
for entry in df_new_car_feature['data'].values[0]:
    heading = entry['heading']
    list_length = len(entry['list'])
    columns[f'{heading}'] = [list_length] * len(df_new_car_feature)

# Convert the dictionary to a DataFrame
car_feature_normalized_data = pd.DataFrame(columns)

# Display the DataFrame
car_feature_normalized_data

      Features  Comfort & Convenience  Interior  Exterior  Safety
0            8                     10         7         5      13
1            9                     10         7         5      13
2            9                     10         7         5      13
3            9                     10         7         5      13
4            9                     10         7         5      13
...        ...                    ...       ...       ...     ...
8364         9                     10         7         5      13
8365         8                     10         7         5      13
8366         9                     10         7         5      13
8367         9                     10         7         5      13
8368         9                     10         7         5      13

[8369 rows x 5 columns]

In [15]:
df_newspecs = data['new_car_specs']
df_new_car_specs = pd.DataFrame(df_newspecs)

# Ensure 'new_car_specs' column is a dictionary
df_new_car_specs['new_car_specs'] = df_new_car_specs['new_car_specs'].apply(ast.literal_eval)

# Normalize the 'new_car_specs' data directly
normalized_data = df_new_car_specs['new_car_specs'].apply(
    lambda specs: {
        **{item['key']: item['value'] for item in specs['top']},
        **{item['key']: item['value'] for section in specs['data'] for item in section['list']}
    }
)

# Convert to DataFrame
car_specification1_normalized_data = pd.json_normalize(normalized_data)

car_specification1_normalized_data

,Mileage,Engine,Max Power,Torque,Seats,Color,Engine Type,Displacement,Max Torque,No of Cylinder,...,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen
0,23.1 kmpl,998 CC,67.04bhp@6000rpm,90Nm,5,White,K10B Engine,998,90Nm@3500rpm,3.0,...,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5,235-litres,NaN,NaN,NaN
1,17 kmpl,1497 CC,121.31bhp@6500rpm,150Nm,5,White,Ti-VCT Petrol Engine,1497,150Nm@4500rpm,3.0,...,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4,352-litres,16,16,NaN
2,23.84 kmpl,1199 CC,84bhp@6000rpm,114Nm,5,Red,Revotron Engine,1199,114Nm@3500rpm,3.0,...,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5,242-litres,14,14,NaN
3,19.1 kmpl,1197 CC,81.86bhp@6000rpm,113.75Nm,5,Others,Kappa VTVT Petrol Engine,1197,113.75Nm@4000rpm,4.0,...,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4,407-litres,14,14,NaN
4,23.65 kmpl,1248 CC,88.5bhp@4000rpm,200Nm,5,Gray,DDiS 200 Diesel Engine,1248,200Nm@1750rpm,4.0,...,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5,353-litres,16,16,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,25.24 kmpl,998 CC,65.71bhp@5500rpm,89Nm,5,Others,K10C,998,89Nm@3500rpm,3.0,...,Ventilated Disc,Drum,NaN,NaN,"Tubeless, Radial",5,313,NaN,NaN,NaN
8365,22.74 kmpl,796 CC,47.3bhp@6000rpm,69Nm,5,Others,F8D Petrol Engine,796,69Nm@3500rpm,3.0,...,Solid Disc,Drum,140 kmph,19 Seconds,Tubeless Tyres,5,177-litres,NaN,NaN,NaN
8366,11.74 kmpl,1796 CC,186bhp@5600rpm,285Nm,5,Others,Blue Efficiency Engine,1796,285Nm@2400-4000rpm,4.0,...,Ventilated Disc,Solid Disc,230km/hr,8.8 Seconds,"Tubeless,Radial",4,475-litres,17,17,NaN
8367,18.5 kmpl,1197 CC,85.80bhp@6000rpm,114Nm,5,Others,K Series Petrol Engine,1197,114Nm@4000rpm,4.0,...,Ventilated Disc,Drum,156 Kmph,15 Seconds,"Tubeless,Radial",5,236-liters,14,14,NaN
8368,19.72 kmpl,1461 CC,108.45bhp@4000rpm,245Nm,5,Others,dCi THP Diesel Engine,1461,245Nm@1750rpm,4.0,...,Disc,Drum,168 Kmph,14.20 Seconds,"Tubeless,Radial",5,410-litres,16,16,NaN

In [16]:
city = data['City']
df_city = pd.DataFrame(city)
df_city

           City
0     Bangalore
1     Bangalore
2     Bangalore
3     Bangalore
4     Bangalore
...         ...
8364    Kolkata
8365    Kolkata
8366    Kolkata
8367    Kolkata
8368    Kolkata

[8369 rows x 1 columns]

In [17]:
full_expanded = pd.concat([car_details_normalized_data,car_overview_normalized_data,car_feature_normalized_data,car_specification1_normalized_data,df_city],axis = 1)
full_expanded

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5,235-litres,NaN,NaN,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,Drum,NaN,NaN,"Tubeless,Radial",4,352-litres,16,16,NaN,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,Drum,150 kmph,14.3 Seconds,Tubeless,5,242-litres,14,14,NaN,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4,407-litres,14,14,NaN,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5,353-litres,16,16,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,Drum,NaN,NaN,"Tubeless, Radial",5,313,NaN,NaN,NaN,Kolkata
8365,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,Drum,140 kmph,19 Seconds,Tubeless Tyres,5,177-litres,NaN,NaN,NaN,Kolkata
8366,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,Solid Disc,230km/hr,8.8 Seconds,"Tubeless,Radial",4,475-litres,17,17,NaN,Kolkata
8367,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,Drum,156 Kmph,15 Seconds,"Tubeless,Radial",5,236-liters,14,14,NaN,Kolkata
8368,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,Drum,168 Kmph,14.20 Seconds,"Tubeless,Radial",5,410-litres,16,16,NaN,Kolkata

In [1]:
full_expanded.to_excel("merged/expanded.xlsx")

NameError: name 'full_expanded' is not defined

# Exploratory Data Analysis

In [1]:
import pandas as pd
import re
import ast

In [2]:
full_expanded = pd.read_excel("merged/expanded.xlsx")

In [3]:
full_expanded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8369 entries, 0 to 8368
Data columns (total 76 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                8369 non-null   int64
 1   it                        8369 non-null   int64
 2   ft                        8369 non-null   object
 3   bt                        8365 non-null   object
 4   km                        8369 non-null   object
 5   transmission              8369 non-null   object
 6   ownerNo                   8369 non-null   int64
 7   owner                     8369 non-null   object
 8   oem                       8369 non-null   object
 9   model                     8369 non-null   object
 10  modelYear                 8369 non-null   int64
 11  centralVariantId          8369 non-null   int64
 12  variantName               8369 non-null   object
 13  price                     8369 non-null   object
 14  priceActual               1670 non-null   object
 15  priceSaving               0 non-null      float64
 16  priceFixedText            0 non-null      float64
 17  trendingText.imgUrl       8369 non-null   object
 18  trendingText.heading      8369 non-null   object
 19  trendingText.desc         8369 non-null   object
 20  Registration Year         8317 non-null   object
 21  Insurance Validity        8365 non-null   object
 22  Fuel Type                 8369 non-null   object
 23  Seats                     8363 non-null   object
 24  Kms Driven                8367 non-null   object
 25  RTO                       7475 non-null   object
 26  Ownership                 8337 non-null   object
 27  Engine Displacement       8365 non-null   object
 28  Transmission              8369 non-null   object
 29  Year of Manufacture       8349 non-null   float64
 30  Features                  8369 non-null   int64
 31  Comfort & Convenience     8369 non-null   int64
 32  Interior                  8369 non-null   int64
 33  Exterior                  8369 non-null   int64
 34  Safety                    8369 non-null   int64
 35  Mileage                   8082 non-null   object
 36  Engine                    8365 non-null   object
 37  Max Power                 8309 non-null   object
 38  Torque                    8309 non-null   object
 39  Seats.1                   8363 non-null   float64
 40  Color                     8366 non-null   object
 41  Engine Type               8074 non-null   object
 42  Displacement              8365 non-null   float64
 43  Max Torque                8309 non-null   object
 44  No of Cylinder            8338 non-null   float64
 45  Values per Cylinder       8318 non-null   float64
 46  Value Configuration       6153 non-null   object
 47  Fuel Suppy System         6642 non-null   object
 48  BoreX Stroke              2405 non-null   object
 49  Compression Ratio         1895 non-null   object
 50  Turbo Charger             7329 non-null   object
 51  Super Charger             6407 non-null   object
 52  Length                    8290 non-null   object
 53  Width                     8286 non-null   object
 54  Height                    8290 non-null   object
 55  Wheel Base                8206 non-null   object
 56  Front Tread               4811 non-null   object
 57  Rear Tread                4799 non-null   object
 58  Kerb Weight               8310 non-null   object
 59  Gross Weight              3828 non-null   object
 60  Gear Box                  8263 non-null   object
 61  Drive Type                6809 non-null   object
 62  Seating Capacity          8363 non-null   float64
 63  Steering Type             8114 non-null   object
 64  Turning Radius            6769 non-null   object
 65  Front Brake Type          8273 non-null   object
 66  Rear Brake Type           8273 non-null   object
 67  Top Speed                 4607 non-null   object
 68  Acceleration              4857 non-null   object
 69  Tyre Type                 8292 non-null   object
 70  No Door Numbers           8358 non-null   float64
 71  Cargo Volumn              6776 non-null   object
 72  Wheel Size                5386 non-null   object
 73  Alloy Wheel Size          5386 non-null   object
 74  Ground Clearance Unladen  515 non-null    object
 75  City                      8369 non-null   object
dtypes: float64(9), int64(10), object(57)
memory usage: 4.9+ MB

In [4]:
#Checking for null value

full_expanded.isnull().sum()

Unnamed: 0                     0
it                             0
ft                             0
bt                             4
km                             0
                            ...
Cargo Volumn                1593
Wheel Size                  2983
Alloy Wheel Size            2983
Ground Clearance Unladen    7854
City                           0
Length: 76, dtype: int64

In [5]:
full_expanded.to_csv("Backup.csv")

In [6]:
full_expanded = pd.read_csv("Backup.csv")

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/950623169.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  full_expanded = pd.read_csv("Backup.csv")

In [7]:
full_expanded

,Unnamed: 0.1,Unnamed: 0,it,ft,bt,km,transmission,ownerNo,owner,oem,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,...,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore
1,1,1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,...,Drum,NaN,NaN,"Tubeless,Radial",4.0,352-litres,16,16,NaN,Bangalore
2,2,2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,...,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,14,14,NaN,Bangalore
3,3,3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,...,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4.0,407-litres,14,14,NaN,Bangalore
4,4,4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,...,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5.0,353-litres,16,16,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,8364,8364,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,...,Drum,NaN,NaN,"Tubeless, Radial",5.0,313,NaN,NaN,NaN,Kolkata
8365,8365,8365,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,...,Drum,140 kmph,19 Seconds,Tubeless Tyres,5.0,177-litres,NaN,NaN,NaN,Kolkata
8366,8366,8366,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,...,Solid Disc,230km/hr,8.8 Seconds,"Tubeless,Radial",4.0,475-litres,17,17,NaN,Kolkata
8367,8367,8367,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,...,Drum,156 Kmph,15 Seconds,"Tubeless,Radial",5.0,236-liters,14,14,NaN,Kolkata
8368,8368,8368,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,...,Drum,168 Kmph,14.20 Seconds,"Tubeless,Radial",5.0,410-litres,16,16,NaN,Kolkata

In [8]:
full_expanded.drop('Unnamed: 0', axis=1, inplace=True)

In [9]:
full_expanded.drop('Unnamed: 0.1', axis=1, inplace=True)

In [10]:
full_expanded

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,Drum,NaN,NaN,"Tubeless,Radial",4.0,352-litres,16,16,NaN,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,14,14,NaN,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4.0,407-litres,14,14,NaN,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5.0,353-litres,16,16,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,Drum,NaN,NaN,"Tubeless, Radial",5.0,313,NaN,NaN,NaN,Kolkata
8365,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,Drum,140 kmph,19 Seconds,Tubeless Tyres,5.0,177-litres,NaN,NaN,NaN,Kolkata
8366,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,Solid Disc,230km/hr,8.8 Seconds,"Tubeless,Radial",4.0,475-litres,17,17,NaN,Kolkata
8367,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,Drum,156 Kmph,15 Seconds,"Tubeless,Radial",5.0,236-liters,14,14,NaN,Kolkata
8368,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,Drum,168 Kmph,14.20 Seconds,"Tubeless,Radial",5.0,410-litres,16,16,NaN,Kolkata

In [11]:
pd.reset_option('display.max_rows', None)
full_expanded

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore
1,0,Petrol,SUV,"32,706",Manual,2,2nd Owner,Ford,Ford Ecosport,2018,...,Drum,NaN,NaN,"Tubeless,Radial",4.0,352-litres,16,16,NaN,Bangalore
2,0,Petrol,Hatchback,"11,949",Manual,1,1st Owner,Tata,Tata Tiago,2018,...,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,14,14,NaN,Bangalore
3,0,Petrol,Sedan,"17,794",Manual,1,1st Owner,Hyundai,Hyundai Xcent,2014,...,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4.0,407-litres,14,14,NaN,Bangalore
4,0,Diesel,SUV,"60,000",Manual,1,1st Owner,Maruti,Maruti SX4 S Cross,2015,...,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5.0,353-litres,16,16,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8364,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Celerio,2022,...,Drum,NaN,NaN,"Tubeless, Radial",5.0,313,NaN,NaN,NaN,Kolkata
8365,0,Petrol,Hatchback,"1,20,000",Manual,1,1st Owner,Maruti,Maruti Alto 800,2014,...,Drum,140 kmph,19 Seconds,Tubeless Tyres,5.0,177-litres,NaN,NaN,NaN,Kolkata
8366,0,Petrol,Sedan,"50,000",Automatic,3,3rd Owner,Mercedes-Benz,Mercedes-Benz C-Class,2011,...,Solid Disc,230km/hr,8.8 Seconds,"Tubeless,Radial",4.0,475-litres,17,17,NaN,Kolkata
8367,0,Petrol,Hatchback,"40,000",Manual,1,1st Owner,Maruti,Maruti Ritz,2012,...,Drum,156 Kmph,15 Seconds,"Tubeless,Radial",5.0,236-liters,14,14,NaN,Kolkata
8368,0,Diesel,SUV,"1,20,000",Manual,2,2nd Owner,Renault,Renault Duster,2017,...,Drum,168 Kmph,14.20 Seconds,"Tubeless,Radial",5.0,410-litres,16,16,NaN,Kolkata

In [12]:
#finding duplocates
duplicate = full_expanded[full_expanded.duplicated(keep=False)]

duplicate

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore
78,0,Petrol,Hatchback,"60,000",Manual,2,2nd Owner,Maruti,Maruti Ritz,2014,...,Drum,156 Kmph,15 Seconds,"Tubeless,Radial",5.0,236-liters,NaN,NaN,NaN,Bangalore
79,0,Petrol,Hatchback,"60,000",Manual,2,2nd Owner,Maruti,Maruti Ritz,2014,...,Drum,156 Kmph,15 Seconds,"Tubeless,Radial",5.0,236-liters,NaN,NaN,NaN,Bangalore
112,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Hyundai,Hyundai Venue,2019,...,Drum,NaN,NaN,Radial,5.0,350,16,16,190mm,Bangalore
114,0,Petrol,SUV,"20,000",Automatic,1,1st Owner,Hyundai,Hyundai Venue,2019,...,Drum,NaN,NaN,Radial,5.0,350,16,16,190mm,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8133,0,Diesel,Sedan,"30,000",Manual,1,1st Owner,Volkswagen,Volkswagen Vento,2014,...,Drum,186 kmph,11.94 Seconds,"Tubeless,Radial",4.0,454-liters,15,15,NaN,Kolkata
8153,0,Petrol,Minivans,"50,000",Manual,3,3rd Owner,Maruti,Maruti Eeco,2010,...,Drum,145 Kmph,15.7 Seconds,Tubeless Tyres,5.0,540-liters,NaN,NaN,NaN,Kolkata
8154,0,Petrol,Minivans,"50,000",Manual,3,3rd Owner,Maruti,Maruti Eeco,2010,...,Drum,145 Kmph,15.7 Seconds,Tubeless Tyres,5.0,540-liters,NaN,NaN,NaN,Kolkata
8338,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Swift,2021,...,Drum,NaN,12.71s,Tubeless,5.0,268,NaN,NaN,NaN,Kolkata
8339,0,Petrol,Hatchback,"10,000",Manual,1,1st Owner,Maruti,Maruti Swift,2021,...,Drum,NaN,12.71s,Tubeless,5.0,268,NaN,NaN,NaN,Kolkata

In [13]:
full_expanded = full_expanded.drop_duplicates(keep='first')
full_expanded.duplicated().sum()

np.int64(0)

In [14]:
full_expanded.to_csv("chatgpt.xlsx")

In [15]:
full_expanded.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'owner', 'oem',
       'model', 'modelYear', 'centralVariantId', 'variantName', 'price',
       'priceActual', 'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'Registration Year',
       'Insurance Validity', 'Fuel Type', 'Seats', 'Kms Driven', 'RTO',
       'Ownership', 'Engine Displacement', 'Transmission',
       'Year of Manufacture', 'Features', 'Comfort & Convenience', 'Interior',
       'Exterior', 'Safety', 'Mileage', 'Engine', 'Max Power', 'Torque',
       'Seats.1', 'Color', 'Engine Type', 'Displacement', 'Max Torque',
       'No of Cylinder', 'Values per Cylinder', 'Value Configuration',
       'Fuel Suppy System', 'BoreX Stroke', 'Compression Ratio',
       'Turbo Charger', 'Super Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Front Tread', 'Rear Tread', 'Kerb Weight',
       'Gross Weight', 'Gear Box', 'Drive Type', 'Seating Capacity',
       'Steering Type', 'Turning Radius', 'Front Brake Type',
       'Rear Brake Type', 'Top Speed', 'Acceleration', 'Tyre Type',
       'No Door Numbers', 'Cargo Volumn', 'Wheel Size', 'Alloy Wheel Size',
       'Ground Clearance Unladen', 'City'],
      dtype='object')

In [16]:
full_expanded['km']

0       1,20,000
1         32,706
2         11,949
3         17,794
4         60,000
          ...
8364      10,000
8365    1,20,000
8366      50,000
8367      40,000
8368    1,20,000
Name: km, Length: 8286, dtype: object

In [17]:
full_expanded['Kms Driven']

0       1,20,000 Kms
1         32,706 Kms
2         11,949 Kms
3         17,794 Kms
4         60,000 Kms
            ...
8364      10,000 Kms
8365    1,20,000 Kms
8366      50,000 Kms
8367      40,000 Kms
8368    1,20,000 Kms
Name: Kms Driven, Length: 8286, dtype: object

In [18]:
#these both km and kms are same data. so dropping one column
full_expanded.drop('Kms Driven', axis=1, inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/3572169841.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('Kms Driven', axis=1, inplace=True)

In [19]:
full_expanded.head(1)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,"1,20,000",Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [20]:
# processing km column
full_expanded['km'] = full_expanded['km'].str.replace(',','').astype(int)
full_expanded.head(1)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/3792007997.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['km'] = full_expanded['km'].str.replace(',','').astype(int)

,it,ft,bt,km,transmission,ownerNo,owner,oem,model,modelYear,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,120000,Manual,3,3rd Owner,Maruti,Maruti Celerio,2015,...,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [21]:
# owner no and owner column meant the same.
# so dropping owner column
full_expanded.drop('owner', axis=1, inplace=True)
full_expanded.head(1)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/1202154065.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('owner', axis=1, inplace=True)

,it,ft,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Petrol,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,...,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [22]:
full_expanded.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price', 'priceActual',
       'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'Registration Year',
       'Insurance Validity', 'Fuel Type', 'Seats', 'RTO', 'Ownership',
       'Engine Displacement', 'Transmission', 'Year of Manufacture',
       'Features', 'Comfort & Convenience', 'Interior', 'Exterior', 'Safety',
       'Mileage', 'Engine', 'Max Power', 'Torque', 'Seats.1', 'Color',
       'Engine Type', 'Displacement', 'Max Torque', 'No of Cylinder',
       'Values per Cylinder', 'Value Configuration', 'Fuel Suppy System',
       'BoreX Stroke', 'Compression Ratio', 'Turbo Charger', 'Super Charger',
       'Length', 'Width', 'Height', 'Wheel Base', 'Front Tread', 'Rear Tread',
       'Kerb Weight', 'Gross Weight', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Top Speed', 'Acceleration',
       'Tyre Type', 'No Door Numbers', 'Cargo Volumn', 'Wheel Size',
       'Alloy Wheel Size', 'Ground Clearance Unladen', 'City'],
      dtype='object')

In [23]:
full_expanded['price']

0          ₹ 4 Lakh
1       ₹ 8.11 Lakh
2       ₹ 5.85 Lakh
3       ₹ 4.62 Lakh
4       ₹ 7.90 Lakh
           ...
8364    ₹ 5.10 Lakh
8365    ₹ 1.80 Lakh
8366    ₹ 5.50 Lakh
8367    ₹ 1.40 Lakh
8368       ₹ 5 Lakh
Name: price, Length: 8286, dtype: object

In [24]:
import re

In [25]:
def convert_amount(amount):
    # Remove '₹' and whitespace
    amount = amount.replace('₹ ', '')
    
    # Handle Crore
    if 'Crore' in amount:
        value = float(re.sub(r'[^\d.]', '', amount))
        return int(value * 10000000)  # Convert crore to integer
    
    # Handle Lakh
    elif 'Lakh' in amount:
        value = float(re.sub(r'[^\d.]', '', amount))
        return int(value * 100000)  # Convert lakh to integer
    
    # Handle plain amount
    else:
        value = int(re.sub(r'[^\d]', '', amount))
        return value

full_expanded['price'] = full_expanded['price'].apply(convert_amount)
full_expanded['price']

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/1026876370.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['price'] = full_expanded['price'].apply(convert_amount)

0       400000
1       811000
2       585000
3       462000
4       790000
         ...
8364    509999
8365    180000
8366    550000
8367    140000
8368    500000
Name: price, Length: 8286, dtype: int64

In [26]:
full_expanded['price'].isnull().sum()

np.int64(0)

In [27]:
full_expanded.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price', 'priceActual',
       'priceSaving', 'priceFixedText', 'trendingText.imgUrl',
       'trendingText.heading', 'trendingText.desc', 'Registration Year',
       'Insurance Validity', 'Fuel Type', 'Seats', 'RTO', 'Ownership',
       'Engine Displacement', 'Transmission', 'Year of Manufacture',
       'Features', 'Comfort & Convenience', 'Interior', 'Exterior', 'Safety',
       'Mileage', 'Engine', 'Max Power', 'Torque', 'Seats.1', 'Color',
       'Engine Type', 'Displacement', 'Max Torque', 'No of Cylinder',
       'Values per Cylinder', 'Value Configuration', 'Fuel Suppy System',
       'BoreX Stroke', 'Compression Ratio', 'Turbo Charger', 'Super Charger',
       'Length', 'Width', 'Height', 'Wheel Base', 'Front Tread', 'Rear Tread',
       'Kerb Weight', 'Gross Weight', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Top Speed', 'Acceleration',
       'Tyre Type', 'No Door Numbers', 'Cargo Volumn', 'Wheel Size',
       'Alloy Wheel Size', 'Ground Clearance Unladen', 'City'],
      dtype='object')

In [28]:
full_expanded['priceActual'].isnull().sum()/len(full_expanded)

np.float64(0.798455225681873)

In [29]:
#priceActual column is having null value of more than 75% so using this in machine learning will reduce the consistency. so dropping that particular column
full_expanded.drop('priceActual',axis=1, inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2422546639.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('priceActual',axis=1, inplace=True)

In [30]:
full_expanded.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price', 'priceSaving',
       'priceFixedText', 'trendingText.imgUrl', 'trendingText.heading',
       'trendingText.desc', 'Registration Year', 'Insurance Validity',
       'Fuel Type', 'Seats', 'RTO', 'Ownership', 'Engine Displacement',
       'Transmission', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety', 'Mileage',
       'Engine', 'Max Power', 'Torque', 'Seats.1', 'Color', 'Engine Type',
       'Displacement', 'Max Torque', 'No of Cylinder', 'Values per Cylinder',
       'Value Configuration', 'Fuel Suppy System', 'BoreX Stroke',
       'Compression Ratio', 'Turbo Charger', 'Super Charger', 'Length',
       'Width', 'Height', 'Wheel Base', 'Front Tread', 'Rear Tread',
       'Kerb Weight', 'Gross Weight', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Top Speed', 'Acceleration',
       'Tyre Type', 'No Door Numbers', 'Cargo Volumn', 'Wheel Size',
       'Alloy Wheel Size', 'Ground Clearance Unladen', 'City'],
      dtype='object')

In [31]:
full_expanded['priceSaving'].isnull().sum()/ len(full_expanded)

np.float64(1.0)

In [32]:
# it has all the rows null so dropping it
full_expanded.drop('priceSaving',axis=1, inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2893228813.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('priceSaving',axis=1, inplace=True)

In [33]:
full_expanded["priceFixedText"].isnull().sum()/len(full_expanded)

np.float64(1.0)

In [34]:
# it has all the rows null so dropping it
full_expanded.drop('priceFixedText',axis=1, inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/3896772592.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('priceFixedText',axis=1, inplace=True)

In [35]:
full_expanded.drop('trendingText.imgUrl',axis=1, inplace=True)
# url is not useful in machine learning and this won't affect the price so dropping

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/3701836981.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('trendingText.imgUrl',axis=1, inplace=True)

In [36]:
full_expanded.drop('trendingText.heading',axis=1, inplace=True)
full_expanded.drop('trendingText.desc',axis=1, inplace=True)

# this all is kind of meta data which is used for describing the data

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2809571572.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('trendingText.heading',axis=1, inplace=True)
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2809571572.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('trendingText.desc',axis=1, inplace=True)

In [37]:
full_expanded.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Seats', 'RTO',
       'Ownership', 'Engine Displacement', 'Transmission',
       'Year of Manufacture', 'Features', 'Comfort & Convenience', 'Interior',
       'Exterior', 'Safety', 'Mileage', 'Engine', 'Max Power', 'Torque',
       'Seats.1', 'Color', 'Engine Type', 'Displacement', 'Max Torque',
       'No of Cylinder', 'Values per Cylinder', 'Value Configuration',
       'Fuel Suppy System', 'BoreX Stroke', 'Compression Ratio',
       'Turbo Charger', 'Super Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Front Tread', 'Rear Tread', 'Kerb Weight',
       'Gross Weight', 'Gear Box', 'Drive Type', 'Seating Capacity',
       'Steering Type', 'Turning Radius', 'Front Brake Type',
       'Rear Brake Type', 'Top Speed', 'Acceleration', 'Tyre Type',
       'No Door Numbers', 'Cargo Volumn', 'Wheel Size', 'Alloy Wheel Size',
       'Ground Clearance Unladen', 'City'],
      dtype='object')

In [38]:
full_expanded['Registration Year'].isnull().sum()

np.int64(52)

In [39]:
full_expanded['Registration Year'] = full_expanded['Registration Year'].str.extract(r'(\d{4})')
full_expanded['Registration Year']

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/1930149420.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Registration Year'] = full_expanded['Registration Year'].str.extract(r'(\d{4})')

0       2015
1       2018
2       2018
3       2014
4       2015
        ...
8364    2022
8365    2014
8366    2011
8367    2012
8368    2017
Name: Registration Year, Length: 8286, dtype: object

In [40]:
full_expanded[full_expanded['Registration Year'].isnull()]
pd.set_option('display.max_columns', None)

In [41]:
full_expanded['Registration Year'] = full_expanded['Registration Year'].astype(float)
mean_registratonyear = full_expanded['Registration Year'].mean()

full_expanded['Registration Year'].fillna(round(mean_registratonyear),inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/57920839.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Registration Year'] = full_expanded['Registration Year'].astype(float)
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/57920839.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['Registration Year'].fillna(round(mean_registratonyear),inplace=True)
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/57920839.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Registration Year'].fillna(round(mean_registratonyear),inplace=True)

In [42]:
full_expanded['Registration Year'] = full_expanded['Registration Year'].astype(int)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/235445177.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Registration Year'] = full_expanded['Registration Year'].astype(int)

In [43]:
full_expanded['Registration Year']

0       2015
1       2018
2       2018
3       2014
4       2015
        ...
8364    2022
8365    2014
8366    2011
8367    2012
8368    2017
Name: Registration Year, Length: 8286, dtype: int64

In [44]:
full_expanded['Registration Year'].isnull().sum()

np.int64(0)

In [45]:
full_expanded['Insurance Validity'].unique()

array(['Third Party insurance', 'Comprehensive', 'Third Party',
       'Zero Dep', nan, '2', '1', 'Not Available'], dtype=object)

In [46]:
full_expanded['Insurance Validity'].value_counts()

Insurance Validity
Third Party insurance    3974
Comprehensive            3148
Third Party               630
Zero Dep                  303
Not Available             223
1                           3
2                           1
Name: count, dtype: int64

In [47]:
full_expanded['Insurance Validity'].fillna('Not Available', inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2694868797.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['Insurance Validity'].fillna('Not Available', inplace=True)
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2694868797.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Insurance Validity'].fillna('Not Available', inplace=True)

In [48]:
full_expanded['Insurance Validity'].isnull().sum()

np.int64(0)

In [49]:
full_expanded[full_expanded['Insurance Validity'] == '1']

,it,ft,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,RTO,Ownership,Engine Displacement,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Seats.1,Color,Engine Type,Displacement,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
524,0,Petrol,Sedan,114321,Manual,2,Maruti,Maruti Ciaz,2016,4007,ZXi Plus,700000,2017,1,Petrol,5 Seats,KA05,Second Owner,1373 cc,Manual,2016.0,9,10,7,5,13,20.73 kmpl,1373 CC,91.1bhp@6000rpm,130Nm,5.0,White,k14B VVT Engine,1373.0,130Nm@4000rpm,4.0,4.0,DOHC,MPFI,73 x 82mm,10.1:1,No,No,4490mm,1730mm,1485mm,2650mm,1495mm,1505mm,1030kg,1490kg,5 Speed,FWD,5.0,Power,5.4 metres,Ventilated Disc,Drum,190 kmph,14 Seconds,"Tubeless, Radial",4.0,510-litres,16,16,NaN,Bangalore
3022,0,Petrol,Hatchback,62150,Manual,1,Hyundai,Hyundai i10,2015,1569,Magna 1.1L,345000,2015,1,Petrol,5 Seats,HR51,First Owner,1086 cc,Manual,2015.0,8,10,7,5,13,19.81 kmpl,1086 CC,68.05bhp@5500rpm,99.04Nm,5.0,Silver,IRDE2 Engine,1086.0,99.04Nm@4500rpm,4.0,3.0,SOHC,MPFI,NaN,NaN,No,No,3585mm,1595mm,1550mm,2380mm,1400mm,1385mm,860kg,NaN,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,165 Kmph,14.3 Seconds,Tubeless,5.0,225-litres,NaN,NaN,NaN,Delhi
6676,0,Diesel,SUV,40220,Manual,1,Mahindra,Mahindra TUV 300,2016,3755,T8,750000,2016,1,Diesel,7 Seats,RJ14,First Owner,1493 cc,Manual,2016.0,9,10,7,5,13,18.49 kmpl,1493 CC,100bhp@3750rpm,240Nm,7.0,Red,mHawk 100 Diesel Engine,1493.0,240Nm@1600-2800rpm,3.0,2.0,NaN,CRDi,NaN,NaN,Yes,No,3995mm,1835mm,1826mm,2680mm,NaN,NaN,1755,2225kg,5 Speed,RWD,7.0,Power,5.35 metres,Disc,Drum,156 Kmph,13.9 Seconds,"Tubeless,Radials",5.0,384-litres,15,15,NaN,Jaipur

In [333]:
full_expanded['Insurance Validity'] == '2'

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
30      False
31      False
32      False
33      False
34      False
35      False
36      False
37      False
38      False
39      False
40      False
41      False
42      False
43      False
44      False
45      False
46      False
47      False
48      False
49      False
50      False
51      False
52      False
53      False
54      False
55      False
56      False
57      False
58      False
59      False
60      False
61      False
62      False
63      False
64      False
65      False
66      False
67      False
68      False
69      False
70      False
71      False
72      False
73      False
74      False
75      False
76      False
77      False
78      False
80      False
81      False
82      False
83      False
84      False
85      False
86      False
87      False
88      False
89      False
90      False
91      False
92      False
93      False
94      False
95      False
96      False
97      False
98      False
99      False
100     False
101     False
102     False
103     False
104     False
105     False
106     False
107     False
108     False
109     False
110     False
111     False
112     False
113     False
115     False
116      True
117     False
118     False
119     False
120     False
121     False
122     False
123     False
125     False
126     False
127     False
128     False
129     False
130     False
131     False
132     False
133     False
134     False
135     False
136     False
137     False
138     False
139     False
140     False
141     False
142     False
143     False
144     False
145     False
146     False
147     False
148     False
149     False
150     False
151     False
152     False
153     False
154     False
155     False
156     False
157     False
158     False
159     False
160     False
161     False
162     False
163     False
164     False
165     False
166     False
167     False
168     False
169     False
170     False
171     False
172     False
173     False
174     False
175     False
176     False
177     False
178     False
179     False
180     False
181     False
182     False
184     False
185     False
186     False
187     False
188     False
189     False
190     False
191     False
192     False
193     False
194     False
195     False
196     False
198     False
199     False
200     False
201     False
202     False
203     False
204     False
205     False
206     False
207     False
208     False
209     False
210     False
211     False
212     False
213     False
214     False
215     False
216     False
217     False
218     False
219     False
220     False
221     False
222     False
223     False
224     False
225     False
226     False
227     False
228     False
229     False
230     False
231     False
232     False
233     False
234     False
235     False
236     False
237     False
238     False
239     False
240     False
241     False
242     False
243     False
244     False
245     False
246     False
247     False
248     False
249     False
250     False
251     False
252     False
253     False
254     False
255     False
256     False
257     False
258     False
259     False
260     False
261     False
262     False
263     False
264     False
265     False
266     False
267     False
268     False
269     False
270     False
271     False
272     False
273     False
274     False
275     False
276     False
277     False
278     False
279     False
280     False
281     False
282     False
283     False
284     False
285     False
286     False
287     False
289     False
290     False
291     False
292     False
293     False
294     False
295     False
296     False
297     False
298     False
299     False
300     False
301     False
302     False
303     False
304     False
305     False
306     False
307     False
308     False
309     False
310     False
311     False
312     False
313     False
314     False
315     False
316     False
317     False
318     False
319     False
320     False
321     False
322     False
323     False
324     False
325     False
326     False
327     False
328     False
329     False
330     False
331     False
332     False
333     False
334     False
335     False
336     False
337     False
338     False
339     False
340     False
341     False
342     False
343     False
344     False
345     False
346     False
347     False
348     False
349     False
350     False
351     False
352     False
353     False
354     False
355     False
356     False
357     False
358     False
359     False
360     False
361     False
362     False
363     False
364     False
365     False
366     False
367     False
368     False
369     False
370     False
371     False
372     False
373     False
374     False
375     False
376     False
377     False
378     False
379     False
380     False
381     False
382     False
383     False
384     False
385     False
386     False
387     False
388     False
389     False
390     False
391     False
392     False
393     False
394     False
395     False
396     False
397     False
398     False
400     False
401     False
402     False
403     False
404     False
405     False
406     False
407     False
408     False
409     False
410     False
412     False
413     False
414     False
415     False
416     False
417     False
418     False
419     False
420     False
421     False
422     False
423     False
424     False
425     False
426     False
427     False
428     False
429     False
430     False
431     False
432     False
433     False
434     False
435     False
436     False
437     False
438     False
439     False
440     False
441     False
442     False
443     False
444     False
445     False
446     False
447     False
448     False
449     False
450     False
451     False
452     False
453     False
454     False
455     False
456     False
457     False
458     False
459     False
460     False
461     False
462     False
463     False
464     False
465     False
466     False
467     False
468     False
469     False
470     False
471     False
472     False
473     False
474     False
475     False
476     False
477     False
478     False
479     False
480     False
481     False
482     False
483     False
484     False
485     False
486     False
487     False
488     False
489     False
490     False
491     False
492     False
493     False
494     False
495     False
496     False
497     False
498     False
499     False
500     False
501     False
502     False
503     False
504     False
505     False
506     False
507     False
508     False
509     False
510     False
511     False
512     False
513     False
514     False
515     False
516     False
517     False
518     False
519     False
520     False
521     False
522     False
523     False
524     False
525     False
526     False
527     False
528     False
529     False
530     False
531     False
532     False
533     False
534     False
535     False
536     False
537     False
538     False
539     False
540     False
541     False
542     False
543     False
544     False
545     False
546     False
547     False
548     False
549     False
550     False
551     False
552     False
553     False
554     False
555     False
556     False
557     False
558     False
559     False
560     False
561     False
562     False
563     False
564     False
565     False
566     False
567     False
568     False
569     False
570     False
571     False
572     False
573     False
574     False
575     False
576     False
577     False
578     False
579     False
580     False
581     False
582     False
583     False
584     False
585     False
586     False
587     False
588     False
589     False
590     False
591     False
592     False
593     False
594     False
595     False
596     False
597     False
598     False
599     False
600     False
601     False
602     False
603     False
604     False
605     False
606     False
607     False
608     False
609     False
610     False
611     False
612     False
613     False
614     False
615     False
616     False
617     False
618     False
619     False
620     False
621     False
622     False
623     False
624     False
625     False
626     False
627     False
628     False
629     False
630     False
631     False
632     False
633     False
634     False
635     False
636     False
637     False
638     False
639     False
640     False
641     False
642     False
643     False
644     False
645     False
646     False
647     False
648     False
649     False
650     False
651     False
652     False
653     False
654     False
655     False
656     False
657     False
658     False
659     False
660     False
661     False
662     False
663     False
664     False
665     False
666     False
667     False
668     False
669     False
670     False
671     False
672     False
673     False
674     False
675     False
676     False
677     False
678     False
679     False
680     False
681     False
682     False
683     False
684     False
685     False
686     False
687     False
688     False
689     False
690     False
691     False
692     False
693     False
694     False
695     False
696     False
697     False
698     False
699     False
700     False
701     False
702     False
703     False
704     False
705     False
706     False
707     False
708     False
709     False
710     False
711     False
712     False
713     False
714     False
715     False
716     False
717     False
718     False
719     False
720     False
721     False
722     False
723     False
724     False
725     False
726     False
727     False
728     False
729     False
730     False
731     False
732     False
733     False
734     False
735     False
736     False
737     False
738     False
739     False
740     False
741     False
742     False
743     False
744     False
745     False
746     False
747     False
748     False
749     False
750     False
751     False
752     False
753     False
754     False
755     False
756     False
757     False
758     False
759     False
760     False
761     False
762     False
763     False
764     False
765     False
766     False
767     False
768     False
769     False
770     False
771     False
772     False
773     False
774     False
775     False
776     False
777     False
778     False
779     False
780     False
781     False
782     False
783     False
784     False
785     False
786     False
787     False
788     False
789     False
790     False
791     False
792     False
793     False
794     False
795     False
796     False
797     False
798     False
799     False
800     False
801     False
802     False
803     False
804     False
805     False
806     False
807     False
809     False
810     False
811     False
812     False
813     False
814     False
815     False
816     False
817     False
818     False
819     False
820     False
821     False
822     False
823     False
824     False
825     False
826     False
827     False
828     False
829     False
830     False
831     False
832     False
833     False
834     False
835     False
836     False
837     False
838     False
839     False
840     False
841     False
842     False
843     False
844     False
845     False
846     False
847     False
848     False
849     False
850     False
851     False
852     False
853     False
854     False
855     False
856     False
857     False
858     False
859     False
860     False
861     False
862     False
863     False
864     False
865     False
866     False
867     False
868     False
869     False
870     False
871     False
872     False
873     False
874     False
875     False
876     False
877     False
878     False
879     False
880     False
881     False
882     False
883     False
884     False
885     False
886     False
887     False
888     False
889     False
891     False
892     False
893     False
894     False
895     False
896     False
897     False
898     False
899     False
900     False
901     False
902     False
903     False
904     False
905     False
906     False
907     False
908     False
909     False
910     False
911     False
912     False
913     False
914     False
915     False
916     False
917     False
918     False
919     False
920     False
921     False
922     False
923     False
924     False
925     False
926     False
927     False
928     False
929     False
930     False
931     False
932     False
933     False
934     False
935     False
936     False
937     False
938     False
939     False
940     False
941     False
943     False
944     False
945     False
946     False
947     False
948     False
949     False
950     False
951     False
952     False
953     False
954     False
955     False
956     False
957     False
958     False
959     False
960     False
962     False
963     False
964     False
965     False
966     False
967     False
968     False
969     False
970     False
971     False
972     False
973     False
974     False
975     False
976     False
977     False
978     False
979     False
980     False
981     False
982     False
983     False
984     False
985     False
986     False
987     False
988     False
989     False
990     False
991     False
992     False
993     False
994     False
995     False
996     False
997     False
998     False
999     False
1000    False
1001    False
1002    False
1003    False
1004    False
1005    False
1006    False
1007    False
1008    False
1009    False
1010    False
1011    False
1012    False
1013    False
1014    False
1015    False
1016    False
1017    False
1018    False
1019    False
1020    False
1021    False
1022    False
1023    False
1024    False
1025    False
1026    False
1027    False
1028    False
1029    False
1030    False
1031    False
1032    False
1033    False
1034    False
1035    False
1036    False
1037    False
1038    False
1039    False
1040    False
1041    False
1042    False
1043    False
1044    False
1045    False
1046    False
1047    False
1048    False
1049    False
1051    False
1052    False
1053    False
1054    False
1055    False
1056    False
1057    False
1058    False
1059    False
1060    False
1061    False
1062    False
1063    False
1064    False
1065    False
1066    False
1067    False
1068    False
1069    False
1070    False
1071    False
1072    False
1073    False
1074    False
1075    False
1076    False
1077    False
1078    False
1079    False
1080    False
1081    False
1082    False
1083    False
1084    False
1085    False
1086    False
1087    False
1088    False
1089    False
1090    False
1091    False
1092    False
1093    False
1094    False
1095    False
1096    False
1097    False
1098    False
1099    False
1100    False
1101    False
1102    False
1103    False
1104    False
1105    False
1106    False
1107    False
1108    False
1109    False
1110    False
1111    False
1112    False
1113    False
1114    False
1115    False
1116    False
1117    False
1118    False
1119    False
1120    False
1121    False
1122    False
1123    False
1124    False
1125    False
1126    False
1127    False
1128    False
1129    False
1130    False
1131    False
1132    False
1133    False
1134    False
1135    False
1136    False
1137    False
1138    False
1139    False
1140    False
1141    False
1142    False
1143    False
1144    False
1145    False
1146    False
1147    False
1148    False
1149    False
1150    False
1151    False
1152    False
1153    False
1154    False
1155    False
1156    False
1157    False
1158    False
1159    False
1160    False
1161    False
1162    False
1163    False
1164    False
1165    False
1166    False
1167    False
1168    False
1169    False
1170    False
1171    False
1172    False
1173    False
1174    False
1175    False
1176    False
1177    False
1178    False
1179    False
1180    False
1181    False
1182    False
1183    False
1184    False
1185    False
1186    False
1187    False
1188    False
1189    False
1190    False
1191    False
1193    False
1194    False
1195    False
1196    False
1197    False
1198    False
1199    False
1200    False
1201    False
1202    False
1203    False
1204    False
1205    False
1206    False
1207    False
1208    False
1209    False
1210    False
1211    False
1212    False
1213    False
1214    False
1215    False
1216    False
1217    False
1218    False
1219    False
1220    False
1221    False
1222    False
1223    False
1224    False
1225    False
1226    False
1227    False
1228    False
1229    False
1230    False
1231    False
1232    False
1233    False
1234    False
1235    False
1236    False
1237    False
1238    False
1239    False
1240    False
1241    False
1242    False
1243    False
1244    False
1245    False
1246    False
1247    False
1248    False
1249    False
1250    False
1251    False
1252    False
1253    False
1254    False
1255    False
1256    False
1257    False
1258    False
1259    False
1260    False
1261    False
1262    False
1263    False
1264    False
1265    False
1266    False
1267    False
1268    False
1269    False
1270    False
1271    False
1272    False
1273    False
1274    False
1275    False
1276    False
1277    False
1278    False
1279    False
1280    False
1281    False
1282    False
1283    False
1284    False
1285    False
1286    False
1287    False
1288    False
1289    False
1290    False
1291    False
1292    False
1293    False
1294    False
1295    False
1296    False
1297    False
1298    False
1299    False
1300    False
1301    False
1302    False
1303    False
1304    False
1305    False
1306    False
1307    False
1308    False
1309    False
1310    False
1311    False
1312    False
1313    False
1314    False
1315    False
1316    False
1317    False
1318    False
1319    False
1320    False
1321    False
1322    False
1323    False
1324    False
1325    False
1326    False
1327    False
1328    False
1329    False
1330    False
1331    False
1332    False
1333    False
1334    False
1335    False
1336    False
1337    False
1338    False
1339    False
1340    False
1341    False
1342    False
1343    False
1344    False
1345    False
1346    False
1347    False
1348    False
1349    False
1350    False
1351    False
1352    False
1353    False
1354    False
1355    False
1356    False
1357    False
1358    False
1359    False
1360    False
1361    False
1362    False
1363    False
1364    False
1365    False
1366    False
1367    False
1368    False
1369    False
1370    False
1371    False
1372    False
1373    False
1374    False
1375    False
1376    False
1377    False
1378    False
1379    False
1380    False
1381    False
1382    False
1383    False
1384    False
1385    False
1386    False
1387    False
1388    False
1389    False
1390    False
1391    False
1392    False
1393    False
1394    False
1395    False
1396    False
1397    False
1398    False
1399    False
1400    False
1401    False
1402    False
1403    False
1404    False
1405    False
1406    False
1407    False
1408    False
1409    False
1410    False
1411    False
1412    False
1413    False
1414    False
1415    False
1416    False
1417    False
1418    False
1419    False
1420    False
1421    False
1422    False
1423    False
1424    False
1425    False
1426    False
1427    False
1428    False
1429    False
1430    False
1431    False
1432    False
1433    False
1434    False
1435    False
1436    False
1437    False
1438    False
1439    False
1440    False
1441    False

In [50]:
#These 1,2 are very feeble and wont affect the data much. hence this will be considered as Not available
# Replace '1' with 'Not Available' in the 'Insurance Validity' column
full_expanded['Insurance Validity'] = full_expanded['Insurance Validity'].replace('1', 'Not Available')
# Replace '2' with 'Not Available' in the 'Insurance Validity' column
full_expanded['Insurance Validity'] = full_expanded['Insurance Validity'].replace('2', 'Not Available')

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/4217595148.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Insurance Validity'] = full_expanded['Insurance Validity'].replace('1', 'Not Available')
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/4217595148.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Insurance Validity'] = full_expanded['Insurance Validity'].replace('2', 'Not Available')

In [51]:
full_expanded['Insurance Validity'].unique()

array(['Third Party insurance', 'Comprehensive', 'Third Party',
       'Zero Dep', 'Not Available'], dtype=object)

In [50]:
# Replace 'Third Party insurance' and 'Third Party' with 'Third Party'
full_expanded['Insurance Validity'] = full_expanded['Insurance Validity'].replace({
    'Third Party insurance': 'Third Party',
    'Third Party': 'Third Party'
})

# Check the unique values after replacement
print(full_expanded['Insurance Validity'].unique())

['Third Party' 'Comprehensive' 'Zero Dep' 'Not Available']

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/4066236379.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Insurance Validity'] = full_expanded['Insurance Validity'].replace({

In [51]:
full_expanded['Insurance Validity'].isnull().sum()

np.int64(0)

In [52]:
full_expanded['Insurance Validity'].value_counts()

Insurance Validity
Third Party      4604
Comprehensive    3148
Zero Dep          303
Not Available     231
Name: count, dtype: int64

In [53]:
full_expanded.columns

Index(['it', 'ft', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Seats', 'RTO',
       'Ownership', 'Engine Displacement', 'Transmission',
       'Year of Manufacture', 'Features', 'Comfort & Convenience', 'Interior',
       'Exterior', 'Safety', 'Mileage', 'Engine', 'Max Power', 'Torque',
       'Seats.1', 'Color', 'Engine Type', 'Displacement', 'Max Torque',
       'No of Cylinder', 'Values per Cylinder', 'Value Configuration',
       'Fuel Suppy System', 'BoreX Stroke', 'Compression Ratio',
       'Turbo Charger', 'Super Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Front Tread', 'Rear Tread', 'Kerb Weight',
       'Gross Weight', 'Gear Box', 'Drive Type', 'Seating Capacity',
       'Steering Type', 'Turning Radius', 'Front Brake Type',
       'Rear Brake Type', 'Top Speed', 'Acceleration', 'Tyre Type',
       'No Door Numbers', 'Cargo Volumn', 'Wheel Size', 'Alloy Wheel Size',
       'Ground Clearance Unladen', 'City'],
      dtype='object')

In [54]:
full_expanded['ft'],full_expanded['Fuel Type']

(0       Petrol
 1       Petrol
 2       Petrol
 3       Petrol
 4       Diesel
          ...
 8364    Petrol
 8365    Petrol
 8366    Petrol
 8367    Petrol
 8368    Diesel
 Name: ft, Length: 8286, dtype: object,
 0       Petrol
 1       Petrol
 2       Petrol
 3       Petrol
 4       Diesel
          ...
 8364    Petrol
 8365    Petrol
 8366    Petrol
 8367    Petrol
 8368    Diesel
 Name: Fuel Type, Length: 8286, dtype: object)

In [55]:
full_expanded['ft'].isnull().sum(),full_expanded['Fuel Type'].isnull().sum()

(np.int64(0), np.int64(0))

In [56]:
#both are same data which is a data redundancy. So removing one column
full_expanded.drop('ft',axis = 1, inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/54097692.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('ft',axis = 1, inplace=True)

In [57]:
full_expanded.columns

Index(['it', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Seats', 'RTO',
       'Ownership', 'Engine Displacement', 'Transmission',
       'Year of Manufacture', 'Features', 'Comfort & Convenience', 'Interior',
       'Exterior', 'Safety', 'Mileage', 'Engine', 'Max Power', 'Torque',
       'Seats.1', 'Color', 'Engine Type', 'Displacement', 'Max Torque',
       'No of Cylinder', 'Values per Cylinder', 'Value Configuration',
       'Fuel Suppy System', 'BoreX Stroke', 'Compression Ratio',
       'Turbo Charger', 'Super Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Front Tread', 'Rear Tread', 'Kerb Weight',
       'Gross Weight', 'Gear Box', 'Drive Type', 'Seating Capacity',
       'Steering Type', 'Turning Radius', 'Front Brake Type',
       'Rear Brake Type', 'Top Speed', 'Acceleration', 'Tyre Type',
       'No Door Numbers', 'Cargo Volumn', 'Wheel Size', 'Alloy Wheel Size',
       'Ground Clearance Unladen', 'City'],
      dtype='object')

In [58]:
full_expanded['Seats'],full_expanded['Seating Capacity']

(0       5 Seats
 1       5 Seats
 2       5 Seats
 3       5 Seats
 4       5 Seats
          ...
 8364    5 Seats
 8365    5 Seats
 8366    5 Seats
 8367    5 Seats
 8368    5 Seats
 Name: Seats, Length: 8286, dtype: object,
 0       5.0
 1       5.0
 2       5.0
 3       5.0
 4       5.0
        ...
 8364    5.0
 8365    5.0
 8366    5.0
 8367    5.0
 8368    5.0
 Name: Seating Capacity, Length: 8286, dtype: float64)

In [59]:
#both are showing same data
full_expanded.drop('Seats', axis=1, inplace = True)

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_15272\3718051682.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('Seats', axis=1, inplace = True)

In [59]:
full_expanded['Seating Capacity'].isnull().sum()/len(full_expanded)

np.float64(0.000724112961622013)

In [60]:
full_expanded['Seating Capacity'].isnull().sum()

np.int64(6)

In [61]:
# there are 6 data only which is having null value which is 0.072 %. It wont have that effect in calculation. so it is converted to mean value
full_expanded['Seating Capacity'].fillna(full_expanded['Seating Capacity'].mean(), inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/171555297.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Seating Capacity'].fillna(full_expanded['Seating Capacity'].mean(), inplace=True)

In [62]:
full_expanded['Seating Capacity'].mean()

np.float64(5.2022946859903385)

In [63]:
full_expanded['Seating Capacity'].isnull().sum()/len(full_expanded)

np.float64(0.0)

In [64]:

s = full_expanded[full_expanded['RTO'].apply(lambda x: isinstance(x, float))]
s

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,...,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
10,0,Hatchback,50000,Manual,1,Maruti,Maruti Baleno,2018,3962,1.2 Delta,...,Drum,180 Kmph,12.36 seconds,"Tubeless,Radial",5.0,339-litres,NaN,NaN,NaN,Bangalore
20,0,Sedan,100000,Automatic,3,BMW,BMW 5 Series,2011,5293,520d Sedan,...,Ventilated discs,226km/hr,8.3 seconds,"Tubeless,Radial",4.0,520 litres,17,17,NaN,Bangalore
24,0,Sedan,50000,Automatic,2,Mercedes-Benz,Mercedes-Benz S-Class,2016,4716,S 500 L,...,Disc,250 kmph,4.8 Seconds,"Tubeless,Radial",4.0,530-litres,19,19,NaN,Bangalore
27,0,Hatchback,30000,Manual,2,Hyundai,Hyundai Santro Xing,2009,1712,GLS LPG,...,Drum,NaN,NaN,"Tubeless,Radial",5.0,NaN,13,13,NaN,Bangalore
33,0,Sedan,50000,Manual,1,Hyundai,Hyundai Xcent,2018,5785,1.2 VTVT SX,...,Drum,172 Kmph,NaN,Tubeless,4.0,407,14,14,NaN,Bangalore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8363,0,Hatchback,30000,Manual,1,Hyundai,Hyundai Santro Xing,2009,1709,GL,...,Drum,141km/hr,16.2 seconds,"Tubeless,Radial",5.0,218 litres,13,13,NaN,Kolkata
8364,0,Hatchback,10000,Manual,1,Maruti,Maruti Celerio,2022,8682,ZXI BSVI,...,Drum,NaN,NaN,"Tubeless, Radial",5.0,313,NaN,NaN,NaN,Kolkata
8365,0,Hatchback,120000,Manual,1,Maruti,Maruti Alto 800,2014,3943,LXI,...,Drum,140 kmph,19 Seconds,Tubeless Tyres,5.0,177-litres,NaN,NaN,NaN,Kolkata
8367,0,Hatchback,40000,Manual,1,Maruti,Maruti Ritz,2012,4144,ZXi,...,Drum,156 Kmph,15 Seconds,"Tubeless,Radial",5.0,236-liters,14,14,NaN,Kolkata
8368,0,SUV,120000,Manual,2,Renault,Renault Duster,2017,5048,110PS Diesel RxZ AWD,...,Drum,168 Kmph,14.20 Seconds,"Tubeless,Radial",5.0,410-litres,16,16,NaN,Kolkata

In [65]:
len(s)/len(full_expanded)

0.10547912140960657

In [66]:
#10.57% of the data are having float value in RTO column which doesnt serve any purpose. The others are telling the state at which the car is been registered. 
# since the city is recorded. the RTO number wont serve big impact in the target. 
full_expanded.drop('RTO',inplace = True, axis=1)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/3670053535.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('RTO',inplace = True, axis=1)

In [67]:
full_expanded.columns

Index(['it', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Seats',
       'Ownership', 'Engine Displacement', 'Transmission',
       'Year of Manufacture', 'Features', 'Comfort & Convenience', 'Interior',
       'Exterior', 'Safety', 'Mileage', 'Engine', 'Max Power', 'Torque',
       'Seats.1', 'Color', 'Engine Type', 'Displacement', 'Max Torque',
       'No of Cylinder', 'Values per Cylinder', 'Value Configuration',
       'Fuel Suppy System', 'BoreX Stroke', 'Compression Ratio',
       'Turbo Charger', 'Super Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Front Tread', 'Rear Tread', 'Kerb Weight',
       'Gross Weight', 'Gear Box', 'Drive Type', 'Seating Capacity',
       'Steering Type', 'Turning Radius', 'Front Brake Type',
       'Rear Brake Type', 'Top Speed', 'Acceleration', 'Tyre Type',
       'No Door Numbers', 'Cargo Volumn', 'Wheel Size', 'Alloy Wheel Size',
       'Ground Clearance Unladen', 'City'],
      dtype='object')

In [68]:
full_expanded['Ownership'] #similar to ownerno

0        Third Owner
1       Second Owner
2        First Owner
3        First Owner
4        First Owner
            ...
8364     First Owner
8365     First Owner
8366     Third Owner
8367     First Owner
8368    Second Owner
Name: Ownership, Length: 8286, dtype: object

In [69]:
full_expanded.drop('Ownership', axis=1, inplace = True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/4105818403.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('Ownership', axis=1, inplace = True)

In [70]:
full_expanded['Engine'],full_expanded['Engine Displacement'] # both are showing the same data

(0        998 CC
 1       1497 CC
 2       1199 CC
 3       1197 CC
 4       1248 CC
          ...
 8364     998 CC
 8365     796 CC
 8366    1796 CC
 8367    1197 CC
 8368    1461 CC
 Name: Engine, Length: 8286, dtype: object,
 0        998 cc
 1       1497 cc
 2       1199 cc
 3       1197 cc
 4       1248 cc
          ...
 8364     998 cc
 8365     796 cc
 8366    1796 cc
 8367    1197 cc
 8368    1461 cc
 Name: Engine Displacement, Length: 8286, dtype: object)

In [71]:
full_expanded['Engine'].isnull().sum(),full_expanded['Engine Displacement'].isnull().sum()

(np.int64(4), np.int64(4))

In [72]:
full_expanded.drop('Engine Displacement',axis=1, inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/3173008523.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded.drop('Engine Displacement',axis=1, inplace=True)

In [73]:
full_expanded['Engine'] = full_expanded['Engine'].str.replace(' cc', '').str.replace(' CC','')
full_expanded['Engine']

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/1176096641.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Engine'] = full_expanded['Engine'].str.replace(' cc', '').str.replace(' CC','')

0        998
1       1497
2       1199
3       1197
4       1248
        ...
8364     998
8365     796
8366    1796
8367    1197
8368    1461
Name: Engine, Length: 8286, dtype: object

In [74]:
full_expanded['Engine'].isnull().sum()

np.int64(4)

In [75]:
full_expanded['Engine'] = full_expanded['Engine'].astype(float)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/67629448.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Engine'] = full_expanded['Engine'].astype(float)

In [76]:
full_expanded['Engine'].fillna(full_expanded['Engine'].mean(), inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/778456629.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['Engine'].fillna(full_expanded['Engine'].mean(), inplace=True)
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/778456629.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Engine'].fillna(full_expanded['Engine'].mean(), inplace=True)

In [77]:
type(full_expanded['Engine'][0])

numpy.float64

In [78]:
full_expanded.columns

Index(['it', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Seats',
       'Transmission', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety', 'Mileage',
       'Engine', 'Max Power', 'Torque', 'Seats.1', 'Color', 'Engine Type',
       'Displacement', 'Max Torque', 'No of Cylinder', 'Values per Cylinder',
       'Value Configuration', 'Fuel Suppy System', 'BoreX Stroke',
       'Compression Ratio', 'Turbo Charger', 'Super Charger', 'Length',
       'Width', 'Height', 'Wheel Base', 'Front Tread', 'Rear Tread',
       'Kerb Weight', 'Gross Weight', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Top Speed', 'Acceleration',
       'Tyre Type', 'No Door Numbers', 'Cargo Volumn', 'Wheel Size',
       'Alloy Wheel Size', 'Ground Clearance Unladen', 'City'],
      dtype='object')

In [80]:
pd.set_option('display.max_rows', None)

In [81]:
full_expanded.isnull().sum()

it                             0
bt                             4
km                             0
transmission                   0
ownerNo                        0
oem                            0
model                          0
modelYear                      0
centralVariantId               0
variantName                    0
price                          0
Registration Year              0
Insurance Validity             0
Fuel Type                      0
Seats                          6
Transmission                   0
Year of Manufacture           20
Features                       0
Comfort & Convenience          0
Interior                       0
Exterior                       0
Safety                         0
Mileage                      285
Engine                         0
Max Power                     60
Torque                        60
Seats.1                        6
Color                          3
Engine Type                  290
Displacement                   4
Max Torque                    60
No of Cylinder                31
Values per Cylinder           51
Value Configuration         2193
Fuel Suppy System           1709
BoreX Stroke                5911
Compression Ratio           6417
Turbo Charger               1029
Super Charger               1940
Length                        79
Width                         83
Height                        79
Wheel Base                   160
Front Tread                 3525
Rear Tread                  3537
Kerb Weight                   59
Gross Weight                4500
Gear Box                     106
Drive Type                  1541
Seating Capacity               0
Steering Type                254
Turning Radius              1588
Front Brake Type              96
Rear Brake Type               96
Top Speed                   3723
Acceleration                3474
Tyre Type                     77
No Door Numbers               11
Cargo Volumn                1572
Wheel Size                  2961
Alloy Wheel Size            2961
Ground Clearance Unladen    7776
City                           0
dtype: int64

In [82]:
pd.set_option('display.max_columns',None)

In [83]:
full_expanded.head(10)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Seats.1,Color,Engine Type,Displacement,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1 kmpl,998.0,67.04bhp@6000rpm,90Nm,5.0,White,K10B Engine,998.0,90Nm@3500rpm,3.0,4.0,DOHC,MPFi,73 X 82 mm,11.0:1,No,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore
1,0,SUV,32706,Manual,2,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,811000,2018,Comprehensive,Petrol,5 Seats,Manual,2018.0,9,10,7,5,13,17 kmpl,1497.0,121.31bhp@6500rpm,150Nm,5.0,White,Ti-VCT Petrol Engine,1497.0,150Nm@4500rpm,3.0,4.0,DOHC,Direct Injection,79 X 76.5 mm,11.0:1,No,No,3998mm,1765mm,1647mm,2519mm,NaN,NaN,1242Kg,1660Kg,5 Speed,FWD,5.0,Power,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4.0,352-litres,16,16,NaN,Bangalore
2,0,Hatchback,11949,Manual,1,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,585000,2018,Comprehensive,Petrol,5 Seats,Manual,2018.0,9,10,7,5,13,23.84 kmpl,1199.0,84bhp@6000rpm,114Nm,5.0,Red,Revotron Engine,1199.0,114Nm@3500rpm,3.0,4.0,DOHC,MPFi,77 X 85.8 mm,10.8:1,No,No,3746mm,1647mm,1535mm,2400mm,1400mm,1420mm,1012kg,NaN,5 Speed,FWD,5.0,Power,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,14,14,NaN,Bangalore
3,0,Sedan,17794,Manual,1,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,462000,2014,Comprehensive,Petrol,5 Seats,Manual,2014.0,9,10,7,5,13,19.1 kmpl,1197.0,81.86bhp@6000rpm,113.75Nm,5.0,Others,Kappa VTVT Petrol Engine,1197.0,113.75Nm@4000rpm,4.0,4.0,DOHC,Direct Injection,NaN,NaN,No,No,3995mm,1660mm,1520mm,2425mm,1479mm,1493mm,1180,NaN,5 Speed,FWD,5.0,Power,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4.0,407-litres,14,14,NaN,Bangalore
4,0,SUV,60000,Manual,1,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,790000,2015,Third Party,Diesel,5 Seats,Manual,2015.0,9,10,7,5,13,23.65 kmpl,1248.0,88.5bhp@4000rpm,200Nm,5.0,Gray,DDiS 200 Diesel Engine,1248.0,200Nm@1750rpm,4.0,4.0,DOHC,NaN,69.6 x 82 mm,NaN,Yes,No,4300mm,1785mm,1595mm,2600mm,NaN,NaN,1230Kg,1670kg,5 Speed,FWD,5.0,Power,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5.0,353-litres,16,16,NaN,Bangalore
5,0,SUV,20000,Manual,1,Jeep,Jeep Compass,2020,5931,2.0 Longitude BSIV,1900000,2020,Third Party,Diesel,5 Seats,Manual,2020.0,9,10,7,5,13,17.1 kmpl,1956.0,170bhp@3750rpm,350Nm,5.0,Others,2.0-Litre 4-Cyl Multijet II Engine,1956.0,350Nm@1750-2500rpm,4.0,4.0,DOHC,CRDI,NaN,NaN,Yes,No,4395mm,1818mm,1640mm,2636mm,NaN,NaN,1551 kgs,NaN,6 Speed,4X2,5.0,power,NaN,Disc,Discs,NaN,NaN,"Radial, Tubless",5.0,408-litres,17,17,NaN,Bangalore
6,0,Hatchback,37772,Manual,1,Datsun,Datsun GO,2017,5223,T Option BSIV,345000,2017,Comprehensive,Petrol,5 Seats,Manual,2017.0,9,10,7,5,13,20.63 kmpl,1198.0,67bhp@5000rpm,104Nm,5.0,Grey,Petrol Engine,1198.0,104Nm@4000rpm,3.0,4.0,DOHC,Electronic Injection System,NaN,NaN,No,No,3785mm,1635mm,1490mm,2450mm,1440mm,1445mm,1070,NaN,5 Speed,FWD,5.0,Power,4.6 metres,Disc,Drum,150 Kmph,13.3 Seconds,Tubeless,5.0,265-litres,NaN,NaN,NaN,Bangalore
7,0,SUV,30000,Automatic,1,Hyundai,Hyundai Venue,2021,6946,SX Plus Turbo DCT BSIV,1200000,2021,Third Party,Petrol,5 Seats,Automatic,2021.0,9,10,7,5,13,18.15 kmpl,998.0,118.35bhp@6000rpm,171.6Nm,5.0,Others,NaN,998.0,171.6Nm@1500-4000rpm,3.0,4.0,NaN,GDi,NaN,NaN,Yes,NaN,3995 mm,1770 mm,1605 mm,2500 mm,NaN,NaN,1440,NaN,7-Speed,FWD,5.0,Power,NaN,Disc,Drum,NaN,NaN,Radial,5.0,350,16,16,190mm,Bangalore
8,0,Sedan,37000,Automatic,1,Maruti,Maruti Ciaz,2018,6555,Alpha Automatic BSIV,960000,2018,Comprehensive,Petrol,5 Seats,Automatic,2018.0,9,10,7,5,13,20.28 kmpl,1462.0,103.25bhp@6000rpm,138Nm,5.0,Maroon,k15B VVT Engine,1462.0,138Nm@4400rpm,4.0,4.0,DOHC,MPFI,74 x 85 mm,NaN,No,No,4490 mm,1730 mm,1485 mm,2650 mm,NaN,NaN,1105,1530Kg,4 Speed,FWD,5.0,Power,5.4 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless, Radial",4.0,510-litres,16,16,NaN,Bangalore
9,0,Hatchback,11949,Manual,1,Tata,Tata Tiago,2017,2985,1.2 Revotron XZ WO Alloy,585000,2018,Comprehensive,Petrol,5 Seats,Manual,2017.0,9,10,7,5,13,23.84 kmpl,1199.0,84bhp@6000rpm,114Nm,5.0,Red,Revotron Engine,1199.0,114Nm@3500rpm,3.0,4.0,DOHC,MPFi,77 X 85.8 mm,10.8:1,No,No,3746mm,1647mm,1535mm,2400mm,1400mm,1420mm,1012kg,NaN,5 Speed,FWD,5.0,Power,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,NaN,NaN,NaN,Bangalore

In [84]:
full_expanded['Mileage'] = full_expanded['Mileage'].str.replace(' kmpl', '')

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_50899/777564277.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  full_expanded['Mileage'] = full_expanded['Mileage'].str.replace(' kmpl', '')

In [85]:
full_expanded['Mileage'].isnull().sum()/len(full_expanded)

np.float64(0.03439536567704562)

In [86]:
full_expanded.to_csv("backup_cleaning_middle.csv")

In [52]:
full_expanded = pd.read_csv("backup_cleaning_middle.csv")

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/4204217462.py:1: DtypeWarning: Columns (23,60,61) have mixed types. Specify dtype option on import or set low_memory=False.
  full_expanded = pd.read_csv("backup_cleaning_middle.csv")

In [53]:
#3.4% of the data are null values. so there are two options one is to remove and another is to replace.
# from the domain knowledge it is understood that kmpl has the highest impact in pricing. so removing is the best option since it can affect machine learning training much
full_expanded.dropna(subset=['Mileage'], inplace=True)

In [54]:
full_expanded['Mileage'].isnull().sum()/len(full_expanded)

np.float64(0.0)

In [55]:
full_expanded.head(1)

,Unnamed: 0,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Seats.1,Color,Engine Type,Displacement,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04bhp@6000rpm,90Nm,5.0,White,K10B Engine,998.0,90Nm@3500rpm,3.0,4.0,DOHC,MPFi,73 X 82 mm,11.0:1,No,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [56]:
full_expanded.drop('Unnamed: 0', axis=1, inplace=True)

In [57]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Seats.1,Color,Engine Type,Displacement,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04bhp@6000rpm,90Nm,5.0,White,K10B Engine,998.0,90Nm@3500rpm,3.0,4.0,DOHC,MPFi,73 X 82 mm,11.0:1,No,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [58]:
full_expanded['Max Power'].isnull().sum()

np.int64(38)

In [59]:

full_expanded['Max Power'] = full_expanded['Max Power'].str.extract(r'(\d+\.?\d*)bhp')[0].astype(float)

In [60]:
full_expanded['Max Power'].isnull().sum()/len(full_expanded)

np.float64(0.046744156980377455)

In [61]:
#4.6 % of the data is missing
# replacing this with mean value
full_expanded['Max Power'].fillna(full_expanded['Max Power'].mean(), inplace=True)
full_expanded['Max Power']

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/1340723466.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['Max Power'].fillna(full_expanded['Max Power'].mean(), inplace=True)

0        67.04
1       121.31
2        84.00
3        81.86
4        88.50
         ...
8281     65.71
8282     47.30
8283    186.00
8284     85.80
8285    108.45
Name: Max Power, Length: 8001, dtype: float64

In [62]:
full_expanded['Max Power'].isnull().sum()

np.int64(0)

In [63]:
full_expanded.columns

Index(['it', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Seats',
       'Transmission', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety', 'Mileage',
       'Engine', 'Max Power', 'Torque', 'Seats.1', 'Color', 'Engine Type',
       'Displacement', 'Max Torque', 'No of Cylinder', 'Values per Cylinder',
       'Value Configuration', 'Fuel Suppy System', 'BoreX Stroke',
       'Compression Ratio', 'Turbo Charger', 'Super Charger', 'Length',
       'Width', 'Height', 'Wheel Base', 'Front Tread', 'Rear Tread',
       'Kerb Weight', 'Gross Weight', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Top Speed', 'Acceleration',
       'Tyre Type', 'No Door Numbers', 'Cargo Volumn', 'Wheel Size',
       'Alloy Wheel Size', 'Ground Clearance Unladen', 'City'],
      dtype='object')

In [64]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Seats.1,Color,Engine Type,Displacement,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90Nm,5.0,White,K10B Engine,998.0,90Nm@3500rpm,3.0,4.0,DOHC,MPFi,73 X 82 mm,11.0:1,No,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [65]:
full_expanded['Torque'].isnull().sum()

np.int64(38)

In [66]:
full_expanded['Torque']

0           90Nm
1          150Nm
2          114Nm
3       113.75Nm
4          200Nm
          ...
8281        89Nm
8282        69Nm
8283       285Nm
8284       114Nm
8285       245Nm
Name: Torque, Length: 8001, dtype: object

In [67]:
full_expanded['Torque'] = full_expanded['Torque'].str.extract(r'^(\d+\.?\d*)').astype(float)
full_expanded['Torque']

0        90.00
1       150.00
2       114.00
3       113.75
4       200.00
         ...
8281     89.00
8282     69.00
8283    285.00
8284    114.00
8285    245.00
Name: Torque, Length: 8001, dtype: float64

In [68]:
full_expanded['Torque'].isnull().sum()

np.int64(38)

In [69]:
full_expanded['Torque'].fillna(full_expanded['Torque'].mean(), inplace=True)
full_expanded['Torque'].isnull().sum()

np.int64(0)

In [70]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Seats.1,Color,Engine Type,Displacement,Max Torque,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,5.0,White,K10B Engine,998.0,90Nm@3500rpm,3.0,4.0,DOHC,MPFi,73 X 82 mm,11.0:1,No,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [71]:
full_expanded['Seating Capacity'].isnull().sum()

np.int64(0)

In [72]:
full_expanded['Seats.1'].isnull().sum()

np.int64(5)

In [73]:
full_expanded.drop('Seats.1',axis=1,inplace=True)

In [74]:
full_expanded['Color'].isnull().sum(), full_expanded['Color'].nunique()

(np.int64(0), 150)

In [75]:
full_expanded['Engine Type'].isnull().sum(), full_expanded['Engine Type'].isnull().sum()/len(full_expanded), full_expanded['Engine Type'].nunique()

(np.int64(240), np.float64(0.029996250468691414), 467)

In [76]:
full_expanded['Engine Type'].value_counts()

Engine Type
In-Line Engine               466
Kappa VTVT Petrol Engine     424
Petrol Engine                313
i-VTEC Petrol Engine         266
i VTEC Engine                199
                            ...
1.2 U2 CRDi diesel             1
In Line Twin Turbo Engine      1
RX270 XDi Diesel Engine        1
mHawk 80 Diesel Engine         1
2AR-FE Petrol Engine           1
Name: count, Length: 467, dtype: int64

In [77]:
# without domain knowledge, it is not advisable to handle the null value with the mode of the engine type.
#almost 3 % of the data is having null value which is converted into NA
full_expanded['Engine Type'].fillna('NA', inplace = True)
full_expanded['Engine Type'].isnull().sum()

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/1677436873.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['Engine Type'].fillna('NA', inplace = True)

np.int64(0)

In [78]:
full_expanded['Displacement'].isnull().sum()

np.int64(1)

In [79]:
full_expanded.dropna(subset=['Displacement'], inplace=True)

In [80]:
full_expanded['Displacement'].isnull().sum()

np.int64(0)

In [81]:
full_expanded['Max Torque']

0             90Nm@3500rpm
1            150Nm@4500rpm
2            114Nm@3500rpm
3         113.75Nm@4000rpm
4            200Nm@1750rpm
               ...
8281          89Nm@3500rpm
8282          69Nm@3500rpm
8283    285Nm@2400-4000rpm
8284         114Nm@4000rpm
8285         245Nm@1750rpm
Name: Max Torque, Length: 8000, dtype: object

In [82]:
full_expanded['Max Torque'] = full_expanded['Max Torque'].str.extract(r'(\d+\.?\d*)Nm')[0]
full_expanded['Max Torque']

0           90
1          150
2          114
3       113.75
4          200
         ...
8281        89
8282        69
8283       285
8284       114
8285       245
Name: Max Torque, Length: 8000, dtype: object

In [83]:
full_expanded['Max Torque'].isnull().sum()/len(full_expanded)

np.float64(0.118625)

In [84]:
# 11% of the data is been missing. so we have 2 options. one is removing the column for analysis or replace it with mean value
# since there is already a torque value is present, max torque value may not give significant impact on the price. so i am dropping that column

full_expanded.drop('Max Torque',axis=1,inplace=True)
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Value Configuration,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,DOHC,MPFi,73 X 82 mm,11.0:1,No,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [85]:
full_expanded["No of Cylinder"].isnull().sum()

np.int64(1)

In [86]:
#only one element is having null value, so dropping that row
full_expanded.dropna(subset=['No of Cylinder'], inplace=True)
full_expanded["No of Cylinder"].isnull().sum()
full_expanded["No of Cylinder"]

0       3.0
1       3.0
2       3.0
3       4.0
4       4.0
       ...
8281    3.0
8282    3.0
8283    4.0
8284    4.0
8285    4.0
Name: No of Cylinder, Length: 7999, dtype: float64

In [87]:
full_expanded["Values per Cylinder"].isnull().sum()/len(full_expanded)

np.float64(0.0026253281660207524)

In [88]:
#only 0.2% of the data is having null values. so it is good to drop it
full_expanded.dropna(subset=['Values per Cylinder'], inplace=True)

In [89]:
full_expanded["Values per Cylinder"].isnull().sum()/len(full_expanded)

np.float64(0.0)

In [90]:
full_expanded["Value Configuration"].isnull().sum()/len(full_expanded), full_expanded["Value Configuration"].unique(), full_expanded["Value Configuration"].nunique()

(np.float64(0.2479318124843319),
 array(['DOHC', nan, 'SOHC', 'DOHC ', 'undefined', 'DOHC with VIS', 'iDSI',
        '23 Modules 69 Cells', 'DOHC with VGT', '16-valve DOHC layout',
        'DOHC with TIS', 'VTEC', 'SOHC '], dtype=object),
 12)

In [91]:
#24% of the data is missing so it is highly recommended to drop the column since domain knowledge is also missing.
full_expanded.drop('Value Configuration',inplace=True, axis=1)
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Fuel Suppy System,BoreX Stroke,Compression Ratio,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,MPFi,73 X 82 mm,11.0:1,No,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [92]:
full_expanded.columns

Index(['it', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Seats',
       'Transmission', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety', 'Mileage',
       'Engine', 'Max Power', 'Torque', 'Color', 'Engine Type', 'Displacement',
       'No of Cylinder', 'Values per Cylinder', 'Fuel Suppy System',
       'BoreX Stroke', 'Compression Ratio', 'Turbo Charger', 'Super Charger',
       'Length', 'Width', 'Height', 'Wheel Base', 'Front Tread', 'Rear Tread',
       'Kerb Weight', 'Gross Weight', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Top Speed', 'Acceleration',
       'Tyre Type', 'No Door Numbers', 'Cargo Volumn', 'Wheel Size',
       'Alloy Wheel Size', 'Ground Clearance Unladen', 'City'],
      dtype='object')

In [93]:
full_expanded["Fuel Suppy System"].isnull().sum(), full_expanded["Fuel Suppy System"].unique(), full_expanded["Fuel Suppy System"].nunique(), full_expanded["Fuel Suppy System"].isnull().sum()/len(full_expanded)

(np.int64(1539),
 array(['MPFi', 'Direct Injection', nan, 'CRDI',
        'Electronic Injection System', 'GDi', 'MPFI', 'PGM - Fi',
        'Direct Injection ', 'PGM-Fi', 'CRDi',
        'Multi Point Fuel Injection', 'MPFI+LPG', 'Common-Rail type',
        'Common Rail Direct Injection (dCi)', 'Multipoint Injection',
        'CDI', 'PFI', 'EFI(Electronic Fuel Injection)', 'MPFI ', 'EFI',
        'Multi-point injection', 'TSI', 'TDCi',
        'Common rail direct injection',
        'PGM-FI (Programmed Fuel Injection)', 'Electronic Fuel Injection',
        'Common Rail Direct Injection', 'Common Rail', 'SEFI',
        'Multi point Fuel Injection', 'MPI', 'Gasoline Direct Injection',
        'MPi', 'Direct Injection Common Rail', 'Dual VVT-i',
        'EFI (Electronic Fuel Injection)', 'SMPI',
        '3 Phase AC Induction Motors', 'Indirect Injection',
        'common rail system', 'GDI', 'PGM-FI (Programmed Fuel Inje',
        'DOHC', 'EGIS', 'Mpfi', 'MFI', 'IDI', 'PGM-FI',
        'Electronic Fuel Injection(EFI)', 'EFIC', 'TFSI', 'EFi',
        'Direct Injection Common Rail ', 'DEDST', 'CRDI ', 'D-4S', 'CNG',
        'Multipoint injection', 'Direct injection',
        'Intelligent-Gas Port Injection', 'DDIS',
        'gasoline direct injection', 'MPFi ', 'ISG', 'MPFI+CNG',
        'Common-Rail Type', 'Advanced Common Rail', 'Ti-VCT',
        'Common Rail ', 'Distribution Type Fuel Injection',
        'Common Rail Diesel', 'Common Rail Injection',
        'PGM-FI (Programmed Fuel Inject', 'Direct Fuel Injection', 'TDi',
        'EFI (Electronic Fuel Injection'], dtype=object),
 76,
 np.float64(0.19290549009776886))

In [94]:
#19% of the data is missing 
# There are two opions one is add a category missing and another is to drop the column
# choosed to drop the column
full_expanded.drop("Fuel Suppy System", axis = 1, inplace=True)

In [95]:
full_expanded['BoreX Stroke'], full_expanded['BoreX Stroke'].isnull().sum()

(0         73 X 82 mm
 1       79 X 76.5 mm
 2       77 X 85.8 mm
 3                NaN
 4       69.6 x 82 mm
             ...
 8281             NaN
 8282             NaN
 8283             NaN
 8284             NaN
 8285             NaN
 Name: BoreX Stroke, Length: 7978, dtype: object,
 np.int64(5626))

In [96]:
full_expanded['BoreX Stroke'].nunique(), full_expanded['BoreX Stroke'].isnull().sum()/len(full_expanded)

(170, np.float64(0.7051892704938582))

In [97]:
# since there is lack in the domain knowledge to understand about 'Borex Stroke' it is better that to avoid this column 
# 70 % of the data is missing. which means there is no use in bringing this column to machine learning
full_expanded.drop('BoreX Stroke',axis=1, inplace=True)
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Compression Ratio,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,11.0:1,No,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [98]:
full_expanded['Compression Ratio'].isnull().sum()/len(full_expanded)

np.float64(0.7699924793181249)

In [99]:
#5.202295 is holding 77% of data which is null 
full_expanded.drop('Compression Ratio',axis=1,inplace=True)
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [100]:
full_expanded['Turbo Charger'].value_counts()

Turbo Charger
No       4130
Yes      2801
Twin       50
NO         20
YES        13
no          8
yes         4
Turbo       2
twin        1
Name: count, dtype: int64

In [101]:
full_expanded['Turbo Charger'].isnull().sum()/len(full_expanded)

np.float64(0.11895211832539483)

In [102]:
# 12% of the data is missing
# replacing the same meaning values
full_expanded['Turbo Charger'] = full_expanded['Turbo Charger'].replace({
    'no': 'No',
    'yes': 'Yes',
    'twin': 'Twin',
    'NO': 'No',
    'YES': 'Yes'
})

In [103]:
full_expanded['Turbo Charger'].value_counts()

Turbo Charger
No       4158
Yes      2818
Twin       51
Turbo       2
Name: count, dtype: int64

In [104]:
# since the null value is high we are planning to keeping it after some correction
full_expanded['Turbo Charger'] = full_expanded['Turbo Charger'].fillna('NA')

In [107]:
full_expanded['Turbo Charger'].isnull().sum()

np.int64(0)

In [108]:
full_expanded['Turbo Charger'].value_counts()

Turbo Charger
No       4158
Yes      2818
NA        949
Twin       51
Turbo       2
Name: count, dtype: int64

In [109]:
full_expanded.head(5)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Super Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.00,White,K10B Engine,998.0,3.0,4.0,No,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore
1,0,SUV,32706,Manual,2,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,811000,2018,Comprehensive,Petrol,5 Seats,Manual,2018.0,9,10,7,5,13,17,1497.0,121.31,150.00,White,Ti-VCT Petrol Engine,1497.0,3.0,4.0,No,No,3998mm,1765mm,1647mm,2519mm,NaN,NaN,1242Kg,1660Kg,5 Speed,FWD,5.0,Power,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4.0,352-litres,16,16,NaN,Bangalore
2,0,Hatchback,11949,Manual,1,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,585000,2018,Comprehensive,Petrol,5 Seats,Manual,2018.0,9,10,7,5,13,23.84,1199.0,84.00,114.00,Red,Revotron Engine,1199.0,3.0,4.0,No,No,3746mm,1647mm,1535mm,2400mm,1400mm,1420mm,1012kg,NaN,5 Speed,FWD,5.0,Power,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,14,14,NaN,Bangalore
3,0,Sedan,17794,Manual,1,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,462000,2014,Comprehensive,Petrol,5 Seats,Manual,2014.0,9,10,7,5,13,19.1,1197.0,81.86,113.75,Others,Kappa VTVT Petrol Engine,1197.0,4.0,4.0,No,No,3995mm,1660mm,1520mm,2425mm,1479mm,1493mm,1180,NaN,5 Speed,FWD,5.0,Power,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4.0,407-litres,14,14,NaN,Bangalore
4,0,SUV,60000,Manual,1,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,790000,2015,Third Party,Diesel,5 Seats,Manual,2015.0,9,10,7,5,13,23.65,1248.0,88.50,200.00,Gray,DDiS 200 Diesel Engine,1248.0,4.0,4.0,Yes,No,4300mm,1785mm,1595mm,2600mm,NaN,NaN,1230Kg,1670kg,5 Speed,FWD,5.0,Power,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5.0,353-litres,16,16,NaN,Bangalore

In [110]:
full_expanded['Super Charger'].isnull().sum()/len(full_expanded)

np.float64(0.20932564552519428)

In [111]:
# since 20% of the data is lost 
# dropping that column
full_expanded.drop('Super Charger',axis=1,inplace=True)

In [112]:
full_expanded.shape

(7978, 56)

In [113]:
full_expanded.to_csv('56.csv')

In [114]:
full_expanded.columns

Index(['it', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Seats',
       'Transmission', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety', 'Mileage',
       'Engine', 'Max Power', 'Torque', 'Color', 'Engine Type', 'Displacement',
       'No of Cylinder', 'Values per Cylinder', 'Turbo Charger', 'Length',
       'Width', 'Height', 'Wheel Base', 'Front Tread', 'Rear Tread',
       'Kerb Weight', 'Gross Weight', 'Gear Box', 'Drive Type',
       'Seating Capacity', 'Steering Type', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Top Speed', 'Acceleration',
       'Tyre Type', 'No Door Numbers', 'Cargo Volumn', 'Wheel Size',
       'Alloy Wheel Size', 'Ground Clearance Unladen', 'City'],
      dtype='object')

In [115]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Front Tread,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715mm,1635mm,1565mm,2425mm,1420mm,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [116]:
full_expanded['Length'].isnull().sum(),full_expanded['Wheel Base'].isnull().sum(),full_expanded['Front Tread'].isnull().sum()

(np.int64(54), np.int64(133), np.int64(3301))

In [117]:
full_expanded.drop('Front Tread',axis=1,inplace=True)

In [118]:
full_expanded['Length'].isnull().sum(),full_expanded['Wheel Base'].isnull().sum()

(np.int64(54), np.int64(133))

In [119]:
full_expanded['Length']

0       3715mm
1       3998mm
2       3746mm
3       3995mm
4       4300mm
         ...
8281    3695mm
8282    3395mm
8283    4591mm
8284    3775mm
8285    4315mm
Name: Length, Length: 7978, dtype: object

In [121]:
# full_expanded['Length'] = full_expanded['Length'].str.extract('(\d+)').astype(int)
full_expanded['Length'] = pd.to_numeric(full_expanded['Length'].str.extract('(\d+)')[0], errors='coerce')
full_expanded['Length']

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/230876425.py:2: SyntaxWarning: invalid escape sequence '\d'
  full_expanded['Length'] = pd.to_numeric(full_expanded['Length'].str.extract('(\d+)')[0], errors='coerce')

0       3715.0
1       3998.0
2       3746.0
3       3995.0
4       4300.0
         ...
8281    3695.0
8282    3395.0
8283    4591.0
8284    3775.0
8285    4315.0
Name: Length, Length: 7978, dtype: float64

In [122]:
full_expanded['Length'].isnull().sum()/len(full_expanded)

np.float64(0.006768613687641012)

In [123]:
full_expanded['Length'].fillna(full_expanded['Length'].mean(),inplace = True)
full_expanded['Length'].isnull().sum()/len(full_expanded)

np.float64(0.0)

In [124]:
full_expanded['Wheel Base']

0       2425mm
1       2519mm
2       2400mm
3       2425mm
4       2600mm
         ...
8281      2435
8282    2360mm
8283    2760mm
8284    2360mm
8285    2673mm
Name: Wheel Base, Length: 7978, dtype: object

In [125]:
full_expanded['Wheel Base'] = pd.to_numeric(full_expanded['Wheel Base'].str.extract('(\d+)')[0], errors='coerce')
full_expanded['Wheel Base']

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2265082680.py:1: SyntaxWarning: invalid escape sequence '\d'
  full_expanded['Wheel Base'] = pd.to_numeric(full_expanded['Wheel Base'].str.extract('(\d+)')[0], errors='coerce')

0       2425.0
1       2519.0
2       2400.0
3       2425.0
4       2600.0
         ...
8281    2435.0
8282    2360.0
8283    2760.0
8284    2360.0
8285    2673.0
Name: Wheel Base, Length: 7978, dtype: float64

In [126]:
full_expanded['Wheel Base'].isnull().sum()/len(full_expanded)

np.float64(0.016670844823263975)

In [127]:
full_expanded['Wheel Base'].fillna(full_expanded['Wheel Base'].mean(),inplace = True)
full_expanded['Wheel Base'].isnull().sum()/len(full_expanded)

np.float64(0.0)

In [128]:
full_expanded.head(5)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Rear Tread,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.00,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635mm,1565mm,2425.0,1410mm,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore
1,0,SUV,32706,Manual,2,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,811000,2018,Comprehensive,Petrol,5 Seats,Manual,2018.0,9,10,7,5,13,17,1497.0,121.31,150.00,White,Ti-VCT Petrol Engine,1497.0,3.0,4.0,No,3998.0,1765mm,1647mm,2519.0,NaN,1242Kg,1660Kg,5 Speed,FWD,5.0,Power,5.3 metres,Ventilated Disc,Drum,NaN,NaN,"Tubeless,Radial",4.0,352-litres,16,16,NaN,Bangalore
2,0,Hatchback,11949,Manual,1,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,585000,2018,Comprehensive,Petrol,5 Seats,Manual,2018.0,9,10,7,5,13,23.84,1199.0,84.00,114.00,Red,Revotron Engine,1199.0,3.0,4.0,No,3746.0,1647mm,1535mm,2400.0,1420mm,1012kg,NaN,5 Speed,FWD,5.0,Power,4.9 meters,Disc,Drum,150 kmph,14.3 Seconds,Tubeless,5.0,242-litres,14,14,NaN,Bangalore
3,0,Sedan,17794,Manual,1,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,462000,2014,Comprehensive,Petrol,5 Seats,Manual,2014.0,9,10,7,5,13,19.1,1197.0,81.86,113.75,Others,Kappa VTVT Petrol Engine,1197.0,4.0,4.0,No,3995.0,1660mm,1520mm,2425.0,1493mm,1180,NaN,5 Speed,FWD,5.0,Power,4.7 metres,Disc,Drum,172km/hr,14.2 Seconds,"Tubeless,Radial",4.0,407-litres,14,14,NaN,Bangalore
4,0,SUV,60000,Manual,1,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,790000,2015,Third Party,Diesel,5 Seats,Manual,2015.0,9,10,7,5,13,23.65,1248.0,88.50,200.00,Gray,DDiS 200 Diesel Engine,1248.0,4.0,4.0,Yes,4300.0,1785mm,1595mm,2600.0,NaN,1230Kg,1670kg,5 Speed,FWD,5.0,Power,5.2 meters,Ventilated Disc,Solid Disc,190 Kmph,12 Seconds,"Tubeless,Radial",5.0,353-litres,16,16,NaN,Bangalore

In [129]:
full_expanded['Rear Tread'].isnull().sum()/len(full_expanded),full_expanded['Kerb Weight'].isnull().sum()/len(full_expanded)

(np.float64(0.41526698420656805), np.float64(0.004512409125094008))

In [130]:
full_expanded.drop('Rear Tread', axis=1, inplace = True)
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gross Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635mm,1565mm,2425.0,835kg,1250kg,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [131]:
full_expanded['Kerb Weight'].isnull().sum()/len(full_expanded),full_expanded['Gross Weight'].isnull().sum()/len(full_expanded)

(np.float64(0.004512409125094008), np.float64(0.5367259964903485))

In [132]:
full_expanded['Kerb Weight'] = pd.to_numeric(full_expanded['Kerb Weight'].str.extract('(\d+)')[0], errors='coerce')
full_expanded['Kerb Weight']

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/3591153312.py:1: SyntaxWarning: invalid escape sequence '\d'
  full_expanded['Kerb Weight'] = pd.to_numeric(full_expanded['Kerb Weight'].str.extract('(\d+)')[0], errors='coerce')

0        835.0
1       1242.0
2       1012.0
3       1180.0
4       1230.0
         ...
8281     810.0
8282     720.0
8283    1585.0
8284    1030.0
8285    1350.0
Name: Kerb Weight, Length: 7978, dtype: float64

In [134]:
full_expanded['Kerb Weight'].isnull().sum()

np.int64(36)

In [135]:
full_expanded['Kerb Weight'] = full_expanded['Kerb Weight'].fillna(full_expanded['Kerb Weight'].mean())

In [136]:
full_expanded['Kerb Weight'].isnull().sum()

np.int64(0)

In [137]:
full_expanded['Gross Weight'].isnull().sum()

np.int64(4282)

In [138]:
full_expanded.drop('Gross Weight',axis=1,inplace=True)
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635mm,1565mm,2425.0,835.0,5 Speed,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [139]:
full_expanded['Gear Box']

0       5 Speed
1        5 Speed
2        5 Speed
3       5 Speed
4        5 Speed
          ...
8281     5-Speed
8282     5 Speed
8283     7 Speed
8284     5 Speed
8285     6 Speed
Name: Gear Box, Length: 7978, dtype: object

In [140]:
full_expanded['Gear Box'] = pd.to_numeric(full_expanded['Gear Box'].str.extract('(\d+)')[0], errors='coerce')
full_expanded['Gear Box']

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/3484542762.py:1: SyntaxWarning: invalid escape sequence '\d'
  full_expanded['Gear Box'] = pd.to_numeric(full_expanded['Gear Box'].str.extract('(\d+)')[0], errors='coerce')

0       5.0
1       5.0
2       5.0
3       5.0
4       5.0
       ...
8281    5.0
8282    5.0
8283    7.0
8284    5.0
8285    6.0
Name: Gear Box, Length: 7978, dtype: float64

In [141]:
full_expanded['Gear Box'].isnull().sum()/ len(full_expanded)

np.float64(0.03284031085485084)

In [142]:
int(full_expanded['Gear Box'].mean())

5

In [143]:
full_expanded['Gear Box'].fillna(int(full_expanded['Gear Box'].mean()),inplace = True)
full_expanded['Gear Box']

0       5.0
1       5.0
2       5.0
3       5.0
4       5.0
       ...
8281    5.0
8282    5.0
8283    7.0
8284    5.0
8285    6.0
Name: Gear Box, Length: 7978, dtype: float64

In [144]:
full_expanded['Gear Box'].isnull().sum()/ len(full_expanded)

np.float64(0.0)

In [145]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635mm,1565mm,2425.0,835.0,5.0,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [146]:
full_expanded['Width'].isnull().sum()/len(full_expanded),full_expanded['Height'].isnull().sum()/len(full_expanded)

(np.float64(0.0072699924793181245), np.float64(0.006768613687641012))

In [147]:
full_expanded['Width'] = pd.to_numeric(full_expanded['Width'].str.extract('(\d+)')[0], errors='coerce')
full_expanded['Height'] = pd.to_numeric(full_expanded['Height'].str.extract('(\d+)')[0], errors='coerce')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2405003406.py:1: SyntaxWarning: invalid escape sequence '\d'
  full_expanded['Width'] = pd.to_numeric(full_expanded['Width'].str.extract('(\d+)')[0], errors='coerce')
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2405003406.py:2: SyntaxWarning: invalid escape sequence '\d'
  full_expanded['Height'] = pd.to_numeric(full_expanded['Height'].str.extract('(\d+)')[0], errors='coerce')

In [148]:
full_expanded['Width'].isnull().sum()/len(full_expanded),full_expanded['Height'].isnull().sum()/len(full_expanded)

(np.float64(0.0072699924793181245), np.float64(0.006768613687641012))

In [149]:
full_expanded['Width'].fillna(full_expanded['Width'].mean(),inplace = True)
full_expanded['Height'].fillna(full_expanded['Height'].mean(),inplace = True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2907563721.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['Width'].fillna(full_expanded['Width'].mean(),inplace = True)
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2907563721.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['Height'].fillna(full_expanded['Height'].mean(),inplace = True)

In [150]:
full_expanded['Width'].isnull().sum()/len(full_expanded),full_expanded['Height'].isnull().sum()/len(full_expanded)

(np.float64(0.0), np.float64(0.0))

In [151]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Drive Type,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,FWD,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [152]:
full_expanded.shape

(7978, 53)

In [153]:
full_expanded['Drive Type']

0        FWD
1        FWD
2        FWD
3       FWD
4        FWD
        ...
8281     NaN
8282     FWD
8283     RWD
8284     FWD
8285     AWD
Name: Drive Type, Length: 7978, dtype: object

In [154]:
full_expanded['Drive Type'].isnull().sum()/len(full_expanded)

np.float64(0.17573326648282778)

In [155]:
# almost 18% of the data is missing. This will affect the learning rate of the machine learning algorithms. So it is been decided to drop
full_expanded.drop('Drive Type',axis=1, inplace=True)
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7 metres,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [156]:
full_expanded['Steering Type'].isnull().sum()/len(full_expanded)

np.float64(0.027951867635999)

In [157]:
# this steering type is a categorical column so i am replacing the null value with mode
full_expanded['Steering Type'].value_counts()

Steering Type
Power         6133
Electric      1352
Electronic     101
Manual          82
Electrical      48
power           29
EPAS             9
electric         1
Name: count, dtype: int64

In [161]:
def steer(steer_type):
    if pd.isna(steer_type):
        return steer_type
    steer_type_lower = steer_type.lower()
    
    if 'electronic' in steer_type_lower or 'electric' in steer_type_lower or 'electrical' in steer_type_lower:
        return 'Electronic'
    elif 'epas' in steer_type_lower:
        return 'EPAS'
    elif 'power' in steer_type_lower:
        return 'Power'
    elif 'manual' in steer_type_lower:
        return 'Manual'
    else:
        return 'Other'

In [162]:
full_expanded['Steering Type'] = full_expanded['Steering Type'].apply(steer)

full_expanded['Steering Type'].value_counts()

Steering Type
Power         6162
Electronic    1502
Manual          82
EPAS             9
Name: count, dtype: int64

In [163]:
full_expanded['Steering Type'].isnull().sum()

np.int64(223)

In [169]:
full_expanded['Steering Type'] = full_expanded['Steering Type'].fillna('Power')
full_expanded['Steering Type'].isnull().sum()

np.int64(0)

In [170]:
full_expanded['Steering Type'].value_counts()

Steering Type
Power         6385
Electronic    1502
Manual          82
EPAS             9
Name: count, dtype: int64

In [171]:
full_expanded['Turning Radius'].isnull().sum()

np.int64(1380)

In [172]:
full_expanded['Turning Radius']

0        4.7 metres
1        5.3 metres
2        4.9 meters
3        4.7 metres
4        5.2 meters
           ...
8281            NaN
8282     4.6 metres
8283    5.42 metres
8284     4.7 metres
8285     5.2 metres
Name: Turning Radius, Length: 7978, dtype: object

In [173]:
full_expanded['Turning Radius'] = pd.to_numeric(full_expanded['Turning Radius'].str.extract('(\d+\.\d+)')[0], errors='coerce')
full_expanded['Turning Radius']

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/3721881218.py:1: SyntaxWarning: invalid escape sequence '\d'
  full_expanded['Turning Radius'] = pd.to_numeric(full_expanded['Turning Radius'].str.extract('(\d+\.\d+)')[0], errors='coerce')

0       4.70
1       5.30
2       4.90
3       4.70
4       5.20
        ...
8281     NaN
8282    4.60
8283    5.42
8284    4.70
8285    5.20
Name: Turning Radius, Length: 7978, dtype: float64

In [174]:
full_expanded['Turning Radius'].isnull().sum()

np.int64(1436)

In [175]:
full_expanded['Turning Radius'].fillna(full_expanded['Turning Radius'].mean(),inplace = True)

In [176]:
full_expanded['Turning Radius'].isnull().sum()

np.int64(0)

In [177]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [178]:
full_expanded['Front Brake Type'].value_counts()

Front Brake Type
Disc                                        5093
Ventilated Disc                             2448
Disc                                          73
Solid Disc                                    63
Ventilated Discs                              61
Disc & Caliper Type                           40
Ventilated Disc                               23
Disk                                          23
Ventilated Disk                               11
Ventilated discs                              10
Disc, 236 mm                                   8
Vantilated Disc                                7
Ventlated Disc                                 6
Drum                                           6
 Disc                                          6
Multilateral Disc                              6
Ventilated DIsc                                5
Ventillated Disc                               3
Mechanical-hydraulic dual circuit              2
Vacuum assisted hydraulic dual circuit w       2
Caliper Ventilated Disc                        2
 Ventilated Disc                               2
disc                                           2
Booster assisted ventilated disc               2
Electric Parking Brake                         2
ventilated Disc                                2
ABS                                            1
solid disc                                     1
Disc,internally ventilated                     1
ventilated disc                                1
Ventilated disc                                1
Discs                                          1
Disc brakes                                    1
Name: count, dtype: int64

In [179]:
full_expanded.to_csv('Before braking.csv')

In [180]:
full_expanded = pd.read_csv('Before braking.csv')

In [183]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Ventilated Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [182]:
full_expanded.drop('Unnamed: 0', axis=1, inplace=True)

In [184]:
#to categorize into major three categories as disc, drum and hydraulic by using the domain knowledge

def categorize_brake_type(brake_type):
    if pd.isna(brake_type):
        return brake_type
    brake_type_lower = brake_type.lower()
    
    if 'disc' in brake_type_lower or 'disk' in brake_type_lower:
        return 'Disc'
    elif 'drum' in brake_type_lower:
        return 'Drum'
    elif 'hydraulic' in brake_type_lower or 'mechanical' in brake_type_lower:
        return 'Hydraulics'
    elif 'electric' in brake_type_lower or 'parking' in brake_type_lower:
        return 'Electric'
    else:
        return 'Other'

full_expanded['Front Brake Type'] = full_expanded['Front Brake Type'].apply(categorize_brake_type)

full_expanded['Front Brake Type'].value_counts()

Front Brake Type
Disc          7902
Drum             6
Hydraulics       4
Electric         2
Other            1
Name: count, dtype: int64

In [185]:
full_expanded['Front Brake Type'].isnull().sum()

np.int64(63)

In [186]:
# Replacing the null value with mode
full_expanded['Front Brake Type'].fillna('Disc',inplace = True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/1651832889.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['Front Brake Type'].fillna('Disc',inplace = True)

In [187]:
full_expanded['Front Brake Type'].isnull().sum()

np.int64(0)

In [188]:
full_expanded['Rear Brake Type'].value_counts()

Rear Brake Type
Drum                                        6285
Disc                                        1074
Ventilated Disc                              154
Solid Disc                                   105
Discs                                         84
Disc & Caliper Type                           40
Leading-Trailing Drum                         29
Self-Adjusting Drum                           25
Ventilated Discs                              23
Leading & Trailing Drum                       14
Ventilated discs                              10
Drums 180 mm                                   8
Disc & Drum                                    7
Self Adjusting Drums                           6
Ventilated Disc                                6
Drum                                           6
Solid Disc                                     5
Drums                                          5
Ventilated Drum                                4
Drum`                                          3
Drum in Discs                                  3
self adjusting drums                           3
drum                                           2
Self Adjusting Drum                            2
Booster assisted drum                          2
Electric Parking Brake                         2
Vacuum assisted hydraulic dual circuit w       2
Mechanical-hydraulic dual circuit              2
Ventialte Disc                                 2
solid disc                                     1
Drum in disc                                   1
Name: count, dtype: int64

In [189]:
full_expanded['Rear Brake Type'] = full_expanded['Rear Brake Type'].apply(categorize_brake_type)
full_expanded['Rear Brake Type'].value_counts()

Rear Brake Type
Drum          6394
Disc          1515
Hydraulics       4
Electric         2
Name: count, dtype: int64

In [190]:
# Replacing null value with mode
full_expanded['Rear Brake Type'].fillna("Drum",inplace=True)
full_expanded['Rear Brake Type'].value_counts()

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/3718436113.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['Rear Brake Type'].fillna("Drum",inplace=True)

Rear Brake Type
Drum          6457
Disc          1515
Hydraulics       4
Electric         2
Name: count, dtype: int64

In [357]:
full_expanded['Rear Brake Type'].isnull().sum()

np.int64(0)

In [191]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Top Speed,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Disc,Drum,150 Kmph,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [192]:
full_expanded['Top Speed'].isnull().sum()/len(full_expanded)

np.float64(0.43920782150915016)

In [193]:
#43% of the data is missing in top speed. so considering dropping the column
full_expanded.drop('Top Speed',axis = 1, inplace=True)

In [194]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Acceleration,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Disc,Drum,15.05 Seconds,"Tubeless, Radial",5.0,235-litres,NaN,NaN,NaN,Bangalore

In [195]:
full_expanded['Acceleration'].isnull().sum()/len(full_expanded)

np.float64(0.4082476811230885)

In [196]:
#43% of the data is missing in Acceleration. so considering dropping the column
full_expanded.drop('Acceleration',axis = 1, inplace=True)

In [197]:
full_expanded['Tyre Type'].isnull().sum()/len(full_expanded)

np.float64(0.006893958385560291)

In [198]:
full_expanded['Tyre Type'].value_counts()

Tyre Type
Tubeless,Radial               4274
Tubeless, Radial              1260
Tubeless                      1159
Tubeless Tyres                 415
Radial, Tubeless               200
Radial                         130
Radial, Tubless                 82
Tubeless Tyres, Radial          61
Tubeless,Radial                 55
Tubeless Radial Tyres           53
Radial,Tubeless                 47
Tubeless,Radials                33
Tubless, Radial                 29
Tubeless,Runflat                18
Tubeless, Runflat               17
Run-Flat                        14
tubeless tyre                   14
Runflat                         12
Runflat Tyres                   11
Tubeless                         7
Runflat Tyre                     5
Radial Tubeless                  5
Radial                           5
Tubeless Tyres Mud Terrain       3
Tubeless Radials Tyre            3
Tubeless. Runflat                2
Tubeless Radial                  2
Tubeless Tyre                    2
Tubeless Tyres All Terrain       1
Tubless,Radial                   1
Runflat,Radial                   1
Radial Tyres                     1
Tubeless, Radials                1
Name: count, dtype: int64

In [199]:
#from the domain knowledge it is understood that, Runflat tyres is a form of tubeless tyres which can run with flat tyres.
# Radial tyre can be rubed or tubeless

In [200]:
def categorize_tyre_type(tyre_type):
    if pd.isna(tyre_type):
        return tyre_type
    tyre_type_lower = tyre_type.lower()
    
    if 'runflat' in tyre_type_lower:
        return 'Runflat'
    elif 'tubeless' in tyre_type_lower or 'tubless' in tyre_type_lower:
        return 'Tubeless'
    elif 'radial' in tyre_type_lower:
        return 'Radial'
    else:
        return 'Other'

In [201]:
full_expanded['Tyre Type'] = full_expanded['Tyre Type'].apply(categorize_tyre_type)
full_expanded['Tyre Type'].value_counts()

Tyre Type
Tubeless    7707
Radial       136
Runflat       66
Other         14
Name: count, dtype: int64

In [202]:
full_expanded['Tyre Type'].isnull().sum()

np.int64(55)

In [203]:
full_expanded['Tyre Type'].fillna('Tubeless',inplace = True)
full_expanded['Tyre Type'].isnull().sum()

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/4178795162.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['Tyre Type'].fillna('Tubeless',inplace = True)

np.int64(0)

In [204]:
# Radial alone is seperated because a radial tyre can either be tubed or tubeless. without the strong domain knowledge we can't decide what to replace with.

In [205]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,5.0,235-litres,NaN,NaN,NaN,Bangalore

In [206]:
full_expanded['No Door Numbers'].value_counts()

No Door Numbers
5.0    5508
4.0    2428
3.0      24
2.0      10
6.0       2
Name: count, dtype: int64

In [207]:
full_expanded['No Door Numbers'].fillna(5.0, inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/1831723710.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  full_expanded['No Door Numbers'].fillna(5.0, inplace=True)

In [208]:
full_expanded['No Door Numbers'].value_counts()

No Door Numbers
5.0    5514
4.0    2428
3.0      24
2.0      10
6.0       2
Name: count, dtype: int64

In [209]:
full_expanded['No Door Numbers'].isnull().sum()

np.int64(0)

In [210]:
full_expanded['Cargo Volumn'].isnull().sum()

np.int64(1376)

In [211]:
full_expanded['Cargo Volumn']

0       235-litres
1       352-litres
2       242-litres
3       407-litres
4       353-litres
           ...
7973           313
7974    177-litres
7975    475-litres
7976    236-liters
7977    410-litres
Name: Cargo Volumn, Length: 7978, dtype: object

In [212]:
full_expanded['Cargo Volumn'] = pd.to_numeric(full_expanded['Cargo Volumn'].str.extract('(\d+)')[0], errors='coerce').fillna(0).astype(int)
full_expanded['Cargo Volumn']

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2224075868.py:1: SyntaxWarning: invalid escape sequence '\d'
  full_expanded['Cargo Volumn'] = pd.to_numeric(full_expanded['Cargo Volumn'].str.extract('(\d+)')[0], errors='coerce').fillna(0).astype(int)

0       235
1       352
2       242
3       407
4       353
       ...
7973    313
7974    177
7975    475
7976    236
7977    410
Name: Cargo Volumn, Length: 7978, dtype: int64

In [213]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,No Door Numbers,Cargo Volumn,Wheel Size,Alloy Wheel Size,Ground Clearance Unladen,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,5.0,235,NaN,NaN,NaN,Bangalore

In [214]:
full_expanded['Wheel Size'].isnull().sum()/len(full_expanded),full_expanded['Alloy Wheel Size'].isnull().sum()/len(full_expanded), full_expanded['Ground Clearance Unladen'].isnull().sum()/len(full_expanded)

(np.float64(0.363374279267987),
 np.float64(0.363374279267987),
 np.float64(0.9365755828528454))

In [215]:
# dropping these three columns since all the three columns are having above 35% of null values
full_expanded.drop('Wheel Size',axis=1,inplace=True)
full_expanded.drop('Alloy Wheel Size',axis=1,inplace=True)
full_expanded.drop('Ground Clearance Unladen',axis=1,inplace=True)

In [216]:
full_expanded.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,No Door Numbers,Cargo Volumn,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,5.0,235,Bangalore

In [217]:
full_expanded.shape

(7978, 47)

In [218]:
full_expanded.columns

Index(['it', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Seats',
       'Transmission', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety', 'Mileage',
       'Engine', 'Max Power', 'Torque', 'Color', 'Engine Type', 'Displacement',
       'No of Cylinder', 'Values per Cylinder', 'Turbo Charger', 'Length',
       'Width', 'Height', 'Wheel Base', 'Kerb Weight', 'Gear Box',
       'Seating Capacity', 'Steering Type', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Tyre Type', 'No Door Numbers',
       'Cargo Volumn', 'City'],
      dtype='object')

In [219]:
full_expanded.to_csv('beforemlcheckpoint.csv')

# Machine Learning pre_processing 
encoder etc.,

In [220]:
df = pd.read_csv('beforemlcheckpoint.csv')

In [221]:
df.isnull().sum()

Unnamed: 0                 0
it                         0
bt                         3
km                         0
transmission               0
ownerNo                    0
oem                        0
model                      0
modelYear                  0
centralVariantId           0
variantName                0
price                      0
Registration Year          0
Insurance Validity         0
Fuel Type                  0
Seats                      4
Transmission               0
Year of Manufacture       13
Features                   0
Comfort & Convenience      0
Interior                   0
Exterior                   0
Safety                     0
Mileage                    0
Engine                     0
Max Power                  0
Torque                     0
Color                      0
Engine Type              239
Displacement               0
No of Cylinder             0
Values per Cylinder        0
Turbo Charger            949
Length                     0
Width                      0
Height                     0
Wheel Base                 0
Kerb Weight                0
Gear Box                   0
Seating Capacity           0
Steering Type              0
Turning Radius             0
Front Brake Type           0
Rear Brake Type            0
Tyre Type                  0
No Door Numbers            0
Cargo Volumn               0
City                       0
dtype: int64

In [222]:
df.head(4)

,Unnamed: 0,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,No Door Numbers,Cargo Volumn,City
0,0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.00,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,5.0,235,Bangalore
1,1,0,SUV,32706,Manual,2,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,811000,2018,Comprehensive,Petrol,5 Seats,Manual,2018.0,9,10,7,5,13,17,1497.0,121.31,150.00,White,Ti-VCT Petrol Engine,1497.0,3.0,4.0,No,3998.0,1765.0,1647.0,2519.0,1242.0,5.0,5.0,Power,5.3,Disc,Drum,Tubeless,4.0,352,Bangalore
2,2,0,Hatchback,11949,Manual,1,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,585000,2018,Comprehensive,Petrol,5 Seats,Manual,2018.0,9,10,7,5,13,23.84,1199.0,84.00,114.00,Red,Revotron Engine,1199.0,3.0,4.0,No,3746.0,1647.0,1535.0,2400.0,1012.0,5.0,5.0,Power,4.9,Disc,Drum,Tubeless,5.0,242,Bangalore
3,3,0,Sedan,17794,Manual,1,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,462000,2014,Comprehensive,Petrol,5 Seats,Manual,2014.0,9,10,7,5,13,19.1,1197.0,81.86,113.75,Others,Kappa VTVT Petrol Engine,1197.0,4.0,4.0,No,3995.0,1660.0,1520.0,2425.0,1180.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,4.0,407,Bangalore

In [223]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head(4)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,No Door Numbers,Cargo Volumn,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.00,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,5.0,235,Bangalore
1,0,SUV,32706,Manual,2,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,811000,2018,Comprehensive,Petrol,5 Seats,Manual,2018.0,9,10,7,5,13,17,1497.0,121.31,150.00,White,Ti-VCT Petrol Engine,1497.0,3.0,4.0,No,3998.0,1765.0,1647.0,2519.0,1242.0,5.0,5.0,Power,5.3,Disc,Drum,Tubeless,4.0,352,Bangalore
2,0,Hatchback,11949,Manual,1,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,585000,2018,Comprehensive,Petrol,5 Seats,Manual,2018.0,9,10,7,5,13,23.84,1199.0,84.00,114.00,Red,Revotron Engine,1199.0,3.0,4.0,No,3746.0,1647.0,1535.0,2400.0,1012.0,5.0,5.0,Power,4.9,Disc,Drum,Tubeless,5.0,242,Bangalore
3,0,Sedan,17794,Manual,1,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,462000,2014,Comprehensive,Petrol,5 Seats,Manual,2014.0,9,10,7,5,13,19.1,1197.0,81.86,113.75,Others,Kappa VTVT Petrol Engine,1197.0,4.0,4.0,No,3995.0,1660.0,1520.0,2425.0,1180.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,4.0,407,Bangalore

In [224]:
df.dropna(subset=['bt'],inplace=True)

In [225]:
df['Year of Manufacture'].fillna(df['Year of Manufacture'].mean,inplace=True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/654104530.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.mean of 0       2015.0
1       2018.0
2       2018.0
3       2014.0
4       2015.0
         ...
7973    2022.0
7974    2014.0
7975    2011.0
7976    2012.0
7977    2017.0
Name: Year of Manufacture, Length: 7975, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df['Year of Manufacture'].fillna(df['Year of Manufacture'].mean,inplace=True)

In [226]:
df['Engine Type'].isnull().sum()/len(df)
# 3% of data missing

np.float64(0.029968652037617553)

In [227]:
df['Engine Type'].nunique()

464

In [228]:
df.shape

(7975, 47)

In [229]:
# df['Engine Type'] has vast variety of data which opens many dimensions.
# for 8000 rows of data 464 unique value, on average each unique value may have 17 datapoints. which is very less for the machine to understand the relationship between Engine type and Price

In [230]:
# so dropping that column
df.drop('Engine Type', axis=1, inplace=True)

In [231]:
df.isnull().sum()

it                         0
bt                         0
km                         0
transmission               0
ownerNo                    0
oem                        0
model                      0
modelYear                  0
centralVariantId           0
variantName                0
price                      0
Registration Year          0
Insurance Validity         0
Fuel Type                  0
Seats                      4
Transmission               0
Year of Manufacture        0
Features                   0
Comfort & Convenience      0
Interior                   0
Exterior                   0
Safety                     0
Mileage                    0
Engine                     0
Max Power                  0
Torque                     0
Color                      0
Displacement               0
No of Cylinder             0
Values per Cylinder        0
Turbo Charger            946
Length                     0
Width                      0
Height                     0
Wheel Base                 0
Kerb Weight                0
Gear Box                   0
Seating Capacity           0
Steering Type              0
Turning Radius             0
Front Brake Type           0
Rear Brake Type            0
Tyre Type                  0
No Door Numbers            0
Cargo Volumn               0
City                       0
dtype: int64

In [232]:
df['Turbo Charger'].isnull().sum()/len(df)

np.float64(0.11862068965517242)

In [233]:
df['Turbo Charger'].value_counts()

Turbo Charger
No       4158
Yes      2818
Twin       51
Turbo       2
Name: count, dtype: int64

In [234]:
df['Turbo Charger'] = df['Turbo Charger'].fillna('No')
#filling null Value with mode

In [235]:
df['Turbo Charger'].value_counts()

Turbo Charger
No       5104
Yes      2818
Twin       51
Turbo       2
Name: count, dtype: int64

In [236]:
df['Kerb Weight'].fillna(df['Kerb Weight'].mean(),inplace = True)

/var/folders/s3/w_ry2nkj7yg8gd7c39mx7xy00000gn/T/ipykernel_60061/2397958938.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Kerb Weight'].fillna(df['Kerb Weight'].mean(),inplace = True)

In [237]:
df.isnull().sum()

it                       0
bt                       0
km                       0
transmission             0
ownerNo                  0
oem                      0
model                    0
modelYear                0
centralVariantId         0
variantName              0
price                    0
Registration Year        0
Insurance Validity       0
Fuel Type                0
Seats                    4
Transmission             0
Year of Manufacture      0
Features                 0
Comfort & Convenience    0
Interior                 0
Exterior                 0
Safety                   0
Mileage                  0
Engine                   0
Max Power                0
Torque                   0
Color                    0
Displacement             0
No of Cylinder           0
Values per Cylinder      0
Turbo Charger            0
Length                   0
Width                    0
Height                   0
Wheel Base               0
Kerb Weight              0
Gear Box                 0
Seating Capacity         0
Steering Type            0
Turning Radius           0
Front Brake Type         0
Rear Brake Type          0
Tyre Type                0
No Door Numbers          0
Cargo Volumn             0
City                     0
dtype: int64

In [238]:
# ensured there are no null values.

In [241]:
df.drop('Seats',axis=1,inplace=True)

In [242]:
df.isnull().sum()

it                       0
bt                       0
km                       0
transmission             0
ownerNo                  0
oem                      0
model                    0
modelYear                0
centralVariantId         0
variantName              0
price                    0
Registration Year        0
Insurance Validity       0
Fuel Type                0
Transmission             0
Year of Manufacture      0
Features                 0
Comfort & Convenience    0
Interior                 0
Exterior                 0
Safety                   0
Mileage                  0
Engine                   0
Max Power                0
Torque                   0
Color                    0
Displacement             0
No of Cylinder           0
Values per Cylinder      0
Turbo Charger            0
Length                   0
Width                    0
Height                   0
Wheel Base               0
Kerb Weight              0
Gear Box                 0
Seating Capacity         0
Steering Type            0
Turning Radius           0
Front Brake Type         0
Rear Brake Type          0
Tyre Type                0
No Door Numbers          0
Cargo Volumn             0
City                     0
dtype: int64

In [243]:
df.to_csv("readyforml.csv")

In [244]:
df.columns

Index(['it', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'model',
       'modelYear', 'centralVariantId', 'variantName', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Transmission',
       'Year of Manufacture', 'Features', 'Comfort & Convenience', 'Interior',
       'Exterior', 'Safety', 'Mileage', 'Engine', 'Max Power', 'Torque',
       'Color', 'Displacement', 'No of Cylinder', 'Values per Cylinder',
       'Turbo Charger', 'Length', 'Width', 'Height', 'Wheel Base',
       'Kerb Weight', 'Gear Box', 'Seating Capacity', 'Steering Type',
       'Turning Radius', 'Front Brake Type', 'Rear Brake Type', 'Tyre Type',
       'No Door Numbers', 'Cargo Volumn', 'City'],
      dtype='object')

In [246]:
df.shape

(7975, 45)

# Analysis

# Machine Learning

In [402]:
from sklearn.preprocessing import OrdinalEncoder

In [420]:
#converting categorical data into numerical coding using Ordinal Encoder

In [403]:
encoder = OrdinalEncoder()

In [405]:
df.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,No Door Numbers,Cargo Volumn,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,5.0,235,Bangalore

In [407]:
df['bt'].isnull().sum()

np.int64(3)

In [410]:
df.dropna(subset=['bt'],inplace=True)

In [411]:
df['bt'].isnull().sum()

np.int64(0)

In [412]:
df['bt'].unique()

array(['Hatchback', 'SUV', 'Sedan', 'MUV', 'Coupe', 'Minivans',
       'Convertibles', 'Hybrids', 'Wagon', 'Pickup Trucks'], dtype=object)

In [413]:
bt = ['Hatchback', 'SUV', 'Sedan', 'MUV', 'Coupe', 'Minivans',
       'Convertibles', 'Hybrids', 'Wagon', 'Pickup Trucks']

In [415]:
bt_enc = OrdinalEncoder(categories= [bt])

In [416]:
bt_enc

OrdinalEncoder(categories=[['Hatchback', 'SUV', 'Sedan', 'MUV', 'Coupe',
                            'Minivans', 'Convertibles', 'Hybrids', 'Wagon',
                            'Pickup Trucks']])

In [417]:
bt_enc.fit_transform(df[['bt']])

array([[0.],
       [1.],
       [0.],
       ...,
       [2.],
       [0.],
       [1.]])

In [418]:
df['bt'] = bt_enc.fit_transform(df[['bt']])
df.head(1)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Seats,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Engine Type,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,No Door Numbers,Cargo Volumn,City
0,0,0.0,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,5 Seats,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.0,White,K10B Engine,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,5.0,235,Bangalore

In [419]:
df['bt'].unique()

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

[array(['Hatchback', 'SUV', 'Sedan', 'MUV', 'Coupe', 'Minivans',
        'Convertibles', 'Hybrids', 'Wagon', 'Pickup Trucks'], dtype=object)]

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7975 entries, 0 to 7977
Data columns (total 45 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   it                     7975 non-null   int64
 1   bt                     7975 non-null   object
 2   km                     7975 non-null   int64
 3   transmission           7975 non-null   object
 4   ownerNo                7975 non-null   int64
 5   oem                    7975 non-null   object
 6   model                  7975 non-null   object
 7   modelYear              7975 non-null   int64
 8   centralVariantId       7975 non-null   int64
 9   variantName            7975 non-null   object
 10  price                  7975 non-null   int64
 11  Registration Year      7975 non-null   int64
 12  Insurance Validity     7975 non-null   object
 13  Fuel Type              7975 non-null   object
 14  Transmission           7975 non-null   object
 15  Year of Manufacture    7975 non-null   object
 16  Features               7975 non-null   int64
 17  Comfort & Convenience  7975 non-null   int64
 18  Interior               7975 non-null   int64
 19  Exterior               7975 non-null   int64
 20  Safety                 7975 non-null   int64
 21  Mileage                7975 non-null   object
 22  Engine                 7975 non-null   float64
 23  Max Power              7975 non-null   float64
 24  Torque                 7975 non-null   float64
 25  Color                  7975 non-null   object
 26  Displacement           7975 non-null   float64
 27  No of Cylinder         7975 non-null   float64
 28  Values per Cylinder    7975 non-null   float64
 29  Turbo Charger          7975 non-null   object
 30  Length                 7975 non-null   float64
 31  Width                  7975 non-null   float64
 32  Height                 7975 non-null   float64
 33  Wheel Base             7975 non-null   float64
 34  Kerb Weight            7975 non-null   float64
 35  Gear Box               7975 non-null   float64
 36  Seating Capacity       7975 non-null   float64
 37  Steering Type          7975 non-null   object
 38  Turning Radius         7975 non-null   float64
 39  Front Brake Type       7975 non-null   object
 40  Rear Brake Type        7975 non-null   object
 41  Tyre Type              7975 non-null   object
 42  No Door Numbers        7975 non-null   float64
 43  Cargo Volumn           7975 non-null   int64
 44  City                   7975 non-null   object
dtypes: float64(15), int64(13), object(17)
memory usage: 2.8+ MB

In [249]:
df.shape

(7975, 45)

In [250]:
for i in df.columns:
  if (df[i].isnull().sum()) !=0:
    print(i, df[i].isnull().sum())

In [252]:
df.duplicated().sum()

np.int64(19)

In [253]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [254]:
pd.set_option("display.max_columns",None)

In [255]:
df.head(5)

,it,bt,km,transmission,ownerNo,oem,model,modelYear,centralVariantId,variantName,price,Registration Year,Insurance Validity,Fuel Type,Transmission,Year of Manufacture,Features,Comfort & Convenience,Interior,Exterior,Safety,Mileage,Engine,Max Power,Torque,Color,Displacement,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Kerb Weight,Gear Box,Seating Capacity,Steering Type,Turning Radius,Front Brake Type,Rear Brake Type,Tyre Type,No Door Numbers,Cargo Volumn,City
0,0,Hatchback,120000,Manual,3,Maruti,Maruti Celerio,2015,3979,VXI,400000,2015,Third Party,Petrol,Manual,2015.0,8,10,7,5,13,23.1,998.0,67.04,90.00,White,998.0,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,835.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,5.0,235,Bangalore
1,0,SUV,32706,Manual,2,Ford,Ford Ecosport,2018,6087,1.5 Petrol Titanium BSIV,811000,2018,Comprehensive,Petrol,Manual,2018.0,9,10,7,5,13,17,1497.0,121.31,150.00,White,1497.0,3.0,4.0,No,3998.0,1765.0,1647.0,2519.0,1242.0,5.0,5.0,Power,5.3,Disc,Drum,Tubeless,4.0,352,Bangalore
2,0,Hatchback,11949,Manual,1,Tata,Tata Tiago,2018,2983,1.2 Revotron XZ,585000,2018,Comprehensive,Petrol,Manual,2018.0,9,10,7,5,13,23.84,1199.0,84.00,114.00,Red,1199.0,3.0,4.0,No,3746.0,1647.0,1535.0,2400.0,1012.0,5.0,5.0,Power,4.9,Disc,Drum,Tubeless,5.0,242,Bangalore
3,0,Sedan,17794,Manual,1,Hyundai,Hyundai Xcent,2014,1867,1.2 Kappa S Option,462000,2014,Comprehensive,Petrol,Manual,2014.0,9,10,7,5,13,19.1,1197.0,81.86,113.75,Others,1197.0,4.0,4.0,No,3995.0,1660.0,1520.0,2425.0,1180.0,5.0,5.0,Power,4.7,Disc,Drum,Tubeless,4.0,407,Bangalore
4,0,SUV,60000,Manual,1,Maruti,Maruti SX4 S Cross,2015,4277,DDiS 200 Zeta,790000,2015,Third Party,Diesel,Manual,2015.0,9,10,7,5,13,23.65,1248.0,88.50,200.00,Gray,1248.0,4.0,4.0,Yes,4300.0,1785.0,1595.0,2600.0,1230.0,5.0,5.0,Power,5.2,Disc,Disc,Tubeless,5.0,353,Bangalore

In [257]:
df.drop(["model",'centralVariantId', 'variantName'],axis = 1,inplace=True)
# oem details is expresed in variant id and variant name

In [265]:
df.drop(['Kerb Weight'],axis = 1,inplace=True)

In [258]:
df.columns

Index(['it', 'bt', 'km', 'transmission', 'ownerNo', 'oem', 'modelYear',
       'price', 'Registration Year', 'Insurance Validity', 'Fuel Type',
       'Transmission', 'Year of Manufacture', 'Features',
       'Comfort & Convenience', 'Interior', 'Exterior', 'Safety', 'Mileage',
       'Engine', 'Max Power', 'Torque', 'Color', 'Displacement',
       'No of Cylinder', 'Values per Cylinder', 'Turbo Charger', 'Length',
       'Width', 'Height', 'Wheel Base', 'Kerb Weight', 'Gear Box',
       'Seating Capacity', 'Steering Type', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Tyre Type', 'No Door Numbers',
       'Cargo Volumn', 'City'],
      dtype='object')

Types

In [259]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7956 entries, 0 to 7977
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   it                     7956 non-null   int64
 1   bt                     7956 non-null   object
 2   km                     7956 non-null   int64
 3   transmission           7956 non-null   object
 4   ownerNo                7956 non-null   int64
 5   oem                    7956 non-null   object
 6   modelYear              7956 non-null   int64
 7   price                  7956 non-null   int64
 8   Registration Year      7956 non-null   int64
 9   Insurance Validity     7956 non-null   object
 10  Fuel Type              7956 non-null   object
 11  Transmission           7956 non-null   object
 12  Year of Manufacture    7956 non-null   object
 13  Features               7956 non-null   int64
 14  Comfort & Convenience  7956 non-null   int64
 15  Interior               7956 non-null   int64
 16  Exterior               7956 non-null   int64
 17  Safety                 7956 non-null   int64
 18  Mileage                7956 non-null   object
 19  Engine                 7956 non-null   float64
 20  Max Power              7956 non-null   float64
 21  Torque                 7956 non-null   float64
 22  Color                  7956 non-null   object
 23  Displacement           7956 non-null   float64
 24  No of Cylinder         7956 non-null   float64
 25  Values per Cylinder    7956 non-null   float64
 26  Turbo Charger          7956 non-null   object
 27  Length                 7956 non-null   float64
 28  Width                  7956 non-null   float64
 29  Height                 7956 non-null   float64
 30  Wheel Base             7956 non-null   float64
 31  Kerb Weight            7956 non-null   float64
 32  Gear Box               7956 non-null   float64
 33  Seating Capacity       7956 non-null   float64
 34  Steering Type          7956 non-null   object
 35  Turning Radius         7956 non-null   float64
 36  Front Brake Type       7956 non-null   object
 37  Rear Brake Type        7956 non-null   object
 38  Tyre Type              7956 non-null   object
 39  No Door Numbers        7956 non-null   float64
 40  Cargo Volumn           7956 non-null   int64
 41  City                   7956 non-null   object
dtypes: float64(15), int64(12), object(15)
memory usage: 2.6+ MB

In [260]:
df['it'].value_counts()
#It has only one value so not useful

it
0    7956
Name: count, dtype: int64

In [261]:
df.drop("it",axis=1,inplace=True)

In [266]:
df.columns

Index(['bt', 'km', 'transmission', 'ownerNo', 'oem', 'modelYear', 'price',
       'Registration Year', 'Insurance Validity', 'Fuel Type', 'Transmission',
       'Year of Manufacture', 'Features', 'Comfort & Convenience', 'Interior',
       'Exterior', 'Safety', 'Mileage', 'Engine', 'Max Power', 'Torque',
       'Color', 'Displacement', 'No of Cylinder', 'Values per Cylinder',
       'Turbo Charger', 'Length', 'Width', 'Height', 'Wheel Base', 'Gear Box',
       'Seating Capacity', 'Steering Type', 'Turning Radius',
       'Front Brake Type', 'Rear Brake Type', 'Tyre Type', 'No Door Numbers',
       'Cargo Volumn', 'City'],
      dtype='object')

In [268]:
df.shape

(7956, 40)

In [270]:
df.drop(["Cargo Volumn"],axis=1,inplace=True)

In [271]:
df.drop(["Registration Year"],axis=1,inplace=True)
df.drop(["Year of Manufacture"],axis=1,inplace=True)
#since the the above 2 columns and model year have the same value

In [272]:
df.drop('Transmission',axis=1,inplace=True)

In [274]:
df['Safety'].value_counts()

Safety
13    7956
Name: count, dtype: int64

In [275]:
df.drop('Safety',axis=1,inplace=True)

In [276]:
df['Interior'].value_counts()

Interior
7    7956
Name: count, dtype: int64

In [277]:
df.drop('Interior',axis=1,inplace=True)

In [278]:
df['Exterior'].value_counts()

Exterior
5    7956
Name: count, dtype: int64

In [279]:
df.drop('Exterior',axis=1,inplace=True)

In [280]:
df['Comfort & Convenience'].value_counts()

Comfort & Convenience
10    7956
Name: count, dtype: int64

In [281]:
df.drop('Comfort & Convenience',axis=1,inplace=True)

In [283]:
df.drop('Turning Radius',axis=1,inplace=True)

In [285]:
df.columns

Index(['bt', 'km', 'transmission', 'ownerNo', 'oem', 'modelYear', 'price',
       'Insurance Validity', 'Fuel Type', 'Features', 'Mileage', 'Engine',
       'Max Power', 'Torque', 'Color', 'Displacement', 'No of Cylinder',
       'Values per Cylinder', 'Turbo Charger', 'Length', 'Width', 'Height',
       'Wheel Base', 'Gear Box', 'Seating Capacity', 'Steering Type',
       'Front Brake Type', 'Rear Brake Type', 'Tyre Type', 'No Door Numbers',
       'City'],
      dtype='object')

In [286]:
df['Engine'].value_counts()

Engine
1197.0    1574
998.0      629
1199.0     484
1248.0     421
1497.0     417
          ...
1108.0       1
2497.0       1
1299.0       1
4134.0       1
2489.0       1
Name: count, Length: 138, dtype: int64

In [287]:
df['Displacement'].value_counts()

Displacement
1197.0    1574
998.0      629
1199.0     484
1248.0     421
1497.0     417
          ...
1108.0       1
2497.0       1
1299.0       1
4134.0       1
2489.0       1
Name: count, Length: 138, dtype: int64

In [288]:
df.drop('Displacement',axis=1,inplace=True)

In [289]:
df.shape

(7956, 30)

In [290]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7956 entries, 0 to 7977
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   bt                   7956 non-null   object
 1   km                   7956 non-null   int64
 2   transmission         7956 non-null   object
 3   ownerNo              7956 non-null   int64
 4   oem                  7956 non-null   object
 5   modelYear            7956 non-null   int64
 6   price                7956 non-null   int64
 7   Insurance Validity   7956 non-null   object
 8   Fuel Type            7956 non-null   object
 9   Features             7956 non-null   int64
 10  Mileage              7956 non-null   object
 11  Engine               7956 non-null   float64
 12  Max Power            7956 non-null   float64
 13  Torque               7956 non-null   float64
 14  Color                7956 non-null   object
 15  No of Cylinder       7956 non-null   float64
 16  Values per Cylinder  7956 non-null   float64
 17  Turbo Charger        7956 non-null   object
 18  Length               7956 non-null   float64
 19  Width                7956 non-null   float64
 20  Height               7956 non-null   float64
 21  Wheel Base           7956 non-null   float64
 22  Gear Box             7956 non-null   float64
 23  Seating Capacity     7956 non-null   float64
 24  Steering Type        7956 non-null   object
 25  Front Brake Type     7956 non-null   object
 26  Rear Brake Type      7956 non-null   object
 27  Tyre Type            7956 non-null   object
 28  No Door Numbers      7956 non-null   float64
 29  City                 7956 non-null   object
dtypes: float64(12), int64(5), object(13)
memory usage: 1.9+ MB

In [291]:
#converting into singular data type is must for machine learning

In [292]:
df.head(5)

,bt,km,transmission,ownerNo,oem,modelYear,price,Insurance Validity,Fuel Type,Features,Mileage,Engine,Max Power,Torque,Color,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Gear Box,Seating Capacity,Steering Type,Front Brake Type,Rear Brake Type,Tyre Type,No Door Numbers,City
0,Hatchback,120000,Manual,3,Maruti,2015,400000,Third Party,Petrol,8,23.1,998.0,67.04,90.00,White,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,5.0,5.0,Power,Disc,Drum,Tubeless,5.0,Bangalore
1,SUV,32706,Manual,2,Ford,2018,811000,Comprehensive,Petrol,9,17,1497.0,121.31,150.00,White,3.0,4.0,No,3998.0,1765.0,1647.0,2519.0,5.0,5.0,Power,Disc,Drum,Tubeless,4.0,Bangalore
2,Hatchback,11949,Manual,1,Tata,2018,585000,Comprehensive,Petrol,9,23.84,1199.0,84.00,114.00,Red,3.0,4.0,No,3746.0,1647.0,1535.0,2400.0,5.0,5.0,Power,Disc,Drum,Tubeless,5.0,Bangalore
3,Sedan,17794,Manual,1,Hyundai,2014,462000,Comprehensive,Petrol,9,19.1,1197.0,81.86,113.75,Others,4.0,4.0,No,3995.0,1660.0,1520.0,2425.0,5.0,5.0,Power,Disc,Drum,Tubeless,4.0,Bangalore
4,SUV,60000,Manual,1,Maruti,2015,790000,Third Party,Diesel,9,23.65,1248.0,88.50,200.00,Gray,4.0,4.0,Yes,4300.0,1785.0,1595.0,2600.0,5.0,5.0,Power,Disc,Disc,Tubeless,5.0,Bangalore

In [296]:
df['price'].dtype

dtype('int64')

In [298]:
#converting to float
df["price"]= df["price"].astype(float)

In [299]:
df['price'].dtype

dtype('float64')

In [302]:
df['Mileage'].dtype

dtype('O')

In [304]:
df['Mileage'].value_counts()

Mileage
18.9      306
18.6      224
21.4      196
17        186
18        142
         ...
16.12       1
11.21       1
16.34       1
14.025      1
19.0        1
Name: count, Length: 524, dtype: int64

In [305]:
def convert_to_float(value):
    if pd.isna(value):  # Check if the value is NaN
        return value
    else:
        value = value.replace("km/kg", "").replace("kmpl", "").replace(" ", "")

    try:
        return float(value)
    except ValueError:
        return value
df['Mileage'] = df['Mileage'].apply(convert_to_float)

In [306]:
df['Engine']

0        998.0
1       1497.0
2       1199.0
3       1197.0
4       1248.0
         ...
7973     998.0
7974     796.0
7975    1796.0
7976    1197.0
7977    1461.0
Name: Engine, Length: 7956, dtype: float64

In [308]:
def convert_to_int(value):
    try:
        if pd.isna(value):  # Check if the value is NaN
            return value
        else:
            value.replace(" ","")
            return int(value.replace("CC",""))
    except:
        return float(value)
df["Engine"] =df["Engine"].apply(convert_to_int)
df['Engine'].dtype

dtype('float64')

In [310]:
df['Max Power'].dtype

dtype('float64')

In [311]:
df['Torque'].dtype

dtype('float64')

In [313]:
df['No of Cylinder'].dtype

dtype('float64')

In [314]:
df['Values per Cylinder'].dtype

dtype('float64')

In [316]:
df['Length'].dtype

dtype('float64')

In [317]:
df['Width'].dtype

dtype('float64')

In [318]:
df['Height'].dtype

dtype('float64')

In [319]:
df['Wheel Base'].dtype

dtype('float64')

In [320]:
df['No Door Numbers'].dtype

dtype('float64')

In [321]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7956 entries, 0 to 7977
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   bt                   7956 non-null   object
 1   km                   7956 non-null   int64
 2   transmission         7956 non-null   object
 3   ownerNo              7956 non-null   int64
 4   oem                  7956 non-null   object
 5   modelYear            7956 non-null   int64
 6   price                7956 non-null   float64
 7   Insurance Validity   7956 non-null   object
 8   Fuel Type            7956 non-null   object
 9   Features             7956 non-null   int64
 10  Mileage              7956 non-null   float64
 11  Engine               7956 non-null   float64
 12  Max Power            7956 non-null   float64
 13  Torque               7956 non-null   float64
 14  Color                7956 non-null   object
 15  No of Cylinder       7956 non-null   float64
 16  Values per Cylinder  7956 non-null   float64
 17  Turbo Charger        7956 non-null   object
 18  Length               7956 non-null   float64
 19  Width                7956 non-null   float64
 20  Height               7956 non-null   float64
 21  Wheel Base           7956 non-null   float64
 22  Gear Box             7956 non-null   float64
 23  Seating Capacity     7956 non-null   float64
 24  Steering Type        7956 non-null   object
 25  Front Brake Type     7956 non-null   object
 26  Rear Brake Type      7956 non-null   object
 27  Tyre Type            7956 non-null   object
 28  No Door Numbers      7956 non-null   float64
 29  City                 7956 non-null   object
dtypes: float64(14), int64(4), object(12)
memory usage: 1.9+ MB

In [322]:
df.select_dtypes(include='object').columns

Index(['bt', 'transmission', 'oem', 'Insurance Validity', 'Fuel Type', 'Color',
       'Turbo Charger', 'Steering Type', 'Front Brake Type', 'Rear Brake Type',
       'Tyre Type', 'City'],
      dtype='object')

In [323]:
for i in df.select_dtypes(include='object').columns:
  print(i)
  print(df[i].unique())
  print("*****"*4)

bt
['Hatchback' 'SUV' 'Sedan' 'MUV' 'Coupe' 'Minivans' 'Convertibles'
 'Hybrids' 'Wagon' 'Pickup Trucks']
********************
transmission
['Manual' 'Automatic']
********************
oem
['Maruti' 'Ford' 'Tata' 'Hyundai' 'Jeep' 'Datsun' 'Honda' 'Mahindra' 'BMW'
 'Renault' 'Mercedes-Benz' 'Audi' 'Toyota' 'Mini' 'Kia' 'Skoda'
 'Volkswagen' 'Volvo' 'MG' 'Nissan' 'Fiat' 'Mahindra Ssangyong'
 'Mitsubishi' 'Jaguar' 'Land Rover' 'Chevrolet' 'Citroen'
 'Mahindra Renault' 'Isuzu' 'Lexus' 'Porsche']
********************
Insurance Validity
['Third Party' 'Comprehensive' 'Zero Dep' 'Not Available']
********************
Fuel Type
['Petrol' 'Diesel' 'LPG' 'CNG' 'Electric']
********************
Color
['White' 'Red' 'Others' 'Gray' 'Grey' 'Maroon' 'Orange' 'Silver' 'Blue'
 'Brown' 'Yellow' 'Black' 'Golden' 'Green' 'O Purple' 'Other' 'Gold'
 'TITANIUM GREY' 'Violet' 'MODERN STEEL METALLIC' 'PLATINUM WHITE'
 'Golden Brown' 'Aurora Black Pearl' 'Beige' 'Star Dust' 'Flash Red'
 'Purple' 'PLATINUM WHITE PEARL' 'Wine Red' 'Taffeta White' 'Minimal Grey'
 'Fiery Red' 'T Wine' 'Prime Star Gaze' 'TAFETA WHITE' 'P Black'
 'Golden brown' 'METALL' 'MET ECRU BEIGE' 'COPPER' 'TITANIUM' 'CHILL'
 'Burgundy' 'Lunar Silver Metallic' 'SILKY SILVER' 'BERRY RED'
 'PREMIUM AMBER METALLIC' 'R EARTH' 'PLATINUM SILVER' 'ORCHID WHITE PEARL'
 'CARNELIAN RED PEARL' 'POLAR WHITE' 'BEIGE' 'Medium Blue'
 'Alabaster Silver Metallic' 'Carbon Steel' 'Cavern Grey' 'ESPRESO_BRWN'
 'Pearl White' 'Polar White' 'Magma Grey' 'Dark Red' 'Falsa Colour'
 'Cherry' 'Hip Hop Black' 'Nexa Blue' 'Passion Red' 'Cirrus White'
 'Arizona Blue' 'Galaxy Blue' 'Silky Silver' 'Modern Steel Metal'
 'GOLDEN BROWN' 'Burgundy Red Metallic' 'magma gray' 'CBeige'
 'Goldan BRWOON' 'm grey' 'b red' 'Granite Grey' 'urban titanim' 'g brown'
 'beige' 'Rosso Brunello' 'a silver' 'b grey' 'Radiant Red M' 'c bronze'
 'Champagne Mica Metallic' 'Bold Beige Metallic' 'Sleek Silver'
 'Symphony Silver' 'Phantom Black' 'Metallic Magma Grey' 'c brown' 'chill'
 'Metallic Glistening Grey' 'Superior white' 'Modern Steel Metallic'
 'Silky silver' 'Arctic Silver' 'Urban Titanium Metallic' 'Smoke Grey'
 'Pearl Arctic White' 'Bright Silver' 'Porcelain White' 'Tafeta White'
 'Coral White' 'Diamond White' 'Brick Red' 'Carnelian Red Pearl'
 'Mediterranean Blue' 'Mist Silver' 'Gravity Gray' 'Candy White'
 'Metallic Premium silver' 'Glistening Grey' 'Super white'
 'Deep Black Pearl' 'Twilight Blue' 'Caviar Black'
 'Pearl Met. Arctic White' 'Metallic silky silver' 'Pure white' 'StarDust'
 'Alabaster Silver Metallic - Amaze' 'Ray blue' 'Glacier White Pearl'
 'OUTBACK BRONZE' 'Solid Fire Red' 'Daytona Grey' 'Metallic Azure Grey'
 'Moonlight Silver' 'Fire Brick Red' 'Cashmere' 'Pearl Snow White'
 'Light Orange' 'Foliage' 'Sky Blue' 'Off White' 'Bronze' 'G Brown'
 'Parpel' 'Outback Bronze' 'Cherry Red' 'Sunset Red' 'golden brown'
 'Technometgrn+Gryroof' 'Dark Blue' 'Out Back Bronze']
********************
Turbo Charger
['No' 'Yes' 'Twin' 'Turbo']
********************
Steering Type
['Power' 'Electronic' 'EPAS' 'Manual']
********************
Front Brake Type
['Disc' 'Drum' 'Electric' 'Other' 'Hydraulics']
********************
Rear Brake Type
['Drum' 'Disc' 'Electric' 'Hydraulics']
********************
Tyre Type
['Tubeless' 'Radial' 'Runflat' 'Other']
********************
City
['Bangalore' 'Chennai' 'Delhi' 'Hyderabad' 'Jaipur' 'Kolkata']
********************

In [324]:
# the color column needs to be group and spell corrected to avoid over computing and have bad effect on learning

In [325]:
df['Color'] = df['Color'].str.lower().str.strip()

In [327]:
color_mapping = {
    'white': 'white','platinum white': 'white','platinum white pearl': 'white','taffeta white': 'white','superior white': 'white','pure white': 'white','polar white': 'white',
    'porcelain white': 'white','coral white': 'white','diamond white': 'white','pearl arctic white': 'white','pearl met. arctic white': 'white','super white': 'white',

    'red': 'red','flash red': 'red','fiery red': 'red','prime star gaze': 'red','b red': 'red','cherry red': 'red','fire brick red': 'red','passion red': 'red',

    'gray': 'gray','grey': 'gray','minimal grey': 'gray','urban titanium': 'gray','smoke grey': 'gray','gravity gray': 'gray','titanium grey': 'gray','daytona grey': 'gray',
    'metallic azure grey': 'gray','granite grey': 'gray',

    'blue': 'blue','nexa blue': 'blue','ray blue': 'blue','twilight blue': 'blue','sky blue': 'blue','mediterranean blue': 'blue','glacier white pearl': 'blue',
    'galaxy blue': 'blue','medium blue': 'blue',

    'black' : 'black','aurora black pearl': 'black','phantom black': 'black','caviar black': 'black','starry black': 'black',

    'silver': 'silver','light silver': 'silver','silky silver': 'silver','bright silver': 'silver','metallic premium silver': 'silver','arctic silver': 'silver','sleek silver': 'silver',

    'green': 'green','olive green': 'green',

    'golden': 'gold','gold': 'gold','golden brown': 'brown',

    'beige': 'beige','bold beige metallic': 'beige',

    'brown': 'brown','copper': 'brown','bronze': 'brown','espreso_brwn': 'brown',

    'others': 'others','other': 'others','falsa colour': 'others','metall': 'others','met ecru beige': 'others','champagne mica metallic': 'others','bold beige metallic': 'others',
    'carbon steel': 'others',
    "o purple":"purple","modern steel metallic":"others","beige":"white","star dust":"others",'wine red':'red','t wine':'others', 'tafeta white':'white',
    "p black":"black",'titanium':'others',"chill":"others","burgundy":"others","purple":"purple","lunar silver metallic":"silver",
    'berry red':'red','premium amber metallic':'others','r earth':'others','platinum silver':'silver', 'orchid white pearl':'white', 'carnelian red pearl':'red',
    'alabaster silver metallic':'silver','cavern grey':'gray', 'pearl white':'white','magma grey':'gray',
    'dark red':'red','cherry':'red','hip hop black':'black','cirrus white':'white','arizona blue':'blue',
    'modern steel metal':'others','burgundy red metallic':'red','magma gray':'gray','cbeige':'white','goldan brwoon':'brown','m grey':'gray',
    'urban titanim':'others','g brown':'brown','rosso brunello':'others','a silver':'silver','b grey':'gray', 'radiant red m':'red','c bronze':'others','metallic magma grey':'gray',
    'c brown':'brown','metallic glistening grey':'gray','urban titanium metallic':'others','violet':'purple','tafeta white':'white','carnelian red pearl':'red','brick red':'red',
    'mist silver':'silver','candy white':'white','glistening grey':'gray','deep black pearl':'black',
    'metallic silky silver':'silver', 'stardust':'others','alabaster silver metallic - amaze':'silver', 'outback bronze':'others','solid fire red':'red', 'moonlight silver':'silver',
    'cashmere':'others','pearl snow white':'white','light orange':'orange','foliage':'others', 'off white':'white','parpel':'others','sunset red':'red',
    'silicon silver':'silver','dark blue':'blue','technometgrn+gryroof':'others','out back bronze':'others','symphony silver':'silver'


}

# Apply the mapping to the color column
df['Color'] = df['Color'].replace(color_mapping)

df["Color"].unique()

array(['white', 'red', 'others', 'gray', 'maroon', 'orange', 'silver',
       'blue', 'brown', 'yellow', 'black', 'gold', 'green', 'purple'],
      dtype=object)

In [329]:
for i in df.select_dtypes(include='object').columns:
  print(i)
  print(df[i].unique())
  print("*****"*5)

bt
['Hatchback' 'SUV' 'Sedan' 'MUV' 'Coupe' 'Minivans' 'Convertibles'
 'Hybrids' 'Wagon' 'Pickup Trucks']
*************************
transmission
['Manual' 'Automatic']
*************************
oem
['Maruti' 'Ford' 'Tata' 'Hyundai' 'Jeep' 'Datsun' 'Honda' 'Mahindra' 'BMW'
 'Renault' 'Mercedes-Benz' 'Audi' 'Toyota' 'Mini' 'Kia' 'Skoda'
 'Volkswagen' 'Volvo' 'MG' 'Nissan' 'Fiat' 'Mahindra Ssangyong'
 'Mitsubishi' 'Jaguar' 'Land Rover' 'Chevrolet' 'Citroen'
 'Mahindra Renault' 'Isuzu' 'Lexus' 'Porsche']
*************************
Insurance Validity
['Third Party' 'Comprehensive' 'Zero Dep' 'Not Available']
*************************
Fuel Type
['Petrol' 'Diesel' 'LPG' 'CNG' 'Electric']
*************************
Color
['white' 'red' 'others' 'gray' 'maroon' 'orange' 'silver' 'blue' 'brown'
 'yellow' 'black' 'gold' 'green' 'purple']
*************************
Turbo Charger
['No' 'Yes' 'Twin' 'Turbo']
*************************
Steering Type
['Power' 'Electronic' 'EPAS' 'Manual']
*************************
Front Brake Type
['Disc' 'Drum' 'Electric' 'Other' 'Hydraulics']
*************************
Rear Brake Type
['Drum' 'Disc' 'Electric' 'Hydraulics']
*************************
Tyre Type
['Tubeless' 'Radial' 'Runflat' 'Other']
*************************
City
['Bangalore' 'Chennai' 'Delhi' 'Hyderabad' 'Jaipur' 'Kolkata']
*************************

In [330]:
df.head()

,bt,km,transmission,ownerNo,oem,modelYear,price,Insurance Validity,Fuel Type,Features,Mileage,Engine,Max Power,Torque,Color,No of Cylinder,Values per Cylinder,Turbo Charger,Length,Width,Height,Wheel Base,Gear Box,Seating Capacity,Steering Type,Front Brake Type,Rear Brake Type,Tyre Type,No Door Numbers,City
0,Hatchback,120000,Manual,3,Maruti,2015,400000.0,Third Party,Petrol,8,23.10,998.0,67.04,90.00,white,3.0,4.0,No,3715.0,1635.0,1565.0,2425.0,5.0,5.0,Power,Disc,Drum,Tubeless,5.0,Bangalore
1,SUV,32706,Manual,2,Ford,2018,811000.0,Comprehensive,Petrol,9,17.00,1497.0,121.31,150.00,white,3.0,4.0,No,3998.0,1765.0,1647.0,2519.0,5.0,5.0,Power,Disc,Drum,Tubeless,4.0,Bangalore
2,Hatchback,11949,Manual,1,Tata,2018,585000.0,Comprehensive,Petrol,9,23.84,1199.0,84.00,114.00,red,3.0,4.0,No,3746.0,1647.0,1535.0,2400.0,5.0,5.0,Power,Disc,Drum,Tubeless,5.0,Bangalore
3,Sedan,17794,Manual,1,Hyundai,2014,462000.0,Comprehensive,Petrol,9,19.10,1197.0,81.86,113.75,others,4.0,4.0,No,3995.0,1660.0,1520.0,2425.0,5.0,5.0,Power,Disc,Drum,Tubeless,4.0,Bangalore
4,SUV,60000,Manual,1,Maruti,2015,790000.0,Third Party,Diesel,9,23.65,1248.0,88.50,200.00,gray,4.0,4.0,Yes,4300.0,1785.0,1595.0,2600.0,5.0,5.0,Power,Disc,Disc,Tubeless,5.0,Bangalore

In [331]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in ./.venv/lib/python3.12/site-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (2.1.1)
Requirement already satisfied: scipy>=1.6.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

Detection of outliers

In [332]:
cont = []
cat = []
for i in df.columns:
  if df[i].nunique()>41:
    cont.append(i)
  else:
    cat.append(i)

print(cont,cat)

['km', 'price', 'Mileage', 'Engine', 'Max Power', 'Torque', 'Length', 'Width', 'Height', 'Wheel Base'] ['bt', 'transmission', 'ownerNo', 'oem', 'modelYear', 'Insurance Validity', 'Fuel Type', 'Features', 'Color', 'No of Cylinder', 'Values per Cylinder', 'Turbo Charger', 'Gear Box', 'Seating Capacity', 'Steering Type', 'Front Brake Type', 'Rear Brake Type', 'Tyre Type', 'No Door Numbers', 'City']

In [333]:
df.to_csv("redyml1609.csv")

In [334]:
def remove_outliers(df, columns):
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        df = df[(df[col] >= (Q1 - 1.5 * IQR)) & (df[col] <= (Q3 + 1.5 * IQR))]
    return df

# Apply outlier removal
df = remove_outliers(df, cont)

In [336]:
df.shape

(5408, 30)

Machine Learning

In [337]:
from sklearn.preprocessing import LabelEncoder
import pickle

In [338]:
#encoding
encoders = {}
for column in df.select_dtypes(include='object').columns:
    encoder = LabelEncoder()
    df[column] = encoder.fit_transform(df[column])
    encoders[column] = encoder

with open('label_encoders.pkl', 'wb') as f:
    pickle.dump(encoders, f)